package com.clothmarket.api.catalog;

import java.math.BigDecimal;
import java.util.List;
import org.springframework.stereotype.Component;

@Component
public class MockPlatformAdapter implements PlatformAdapter {
    private static final List<ProductSummary> PRODUCTS = List.of(
        new ProductSummary("CM-MSH-001", "Oversized Black Denim Casual Shirt", "Roadster", "Shirts", "AJIO", new BigDecimal("899"), new BigDecimal("1799"), 4.4, true, "/products/shirts/CM-MSH-001-front.jpg"),
        new ProductSummary("CM-MSH-002", "Classic Oxford Cotton Button-Down Shirt", "Allen Solly", "Shirts", "Myntra", new BigDecimal("1199"), new BigDecimal("2199"), 4.3, true, "/products/shirts/CM-MSH-002-front.jpg"),
        new ProductSummary("CM-MSH-003", "Vintage Plaid Flannel Casual Shirt", "Highlander", "Shirts", "Flipkart", new BigDecimal("649"), new BigDecimal("1599"), 4.2, true, "/products/shirts/CM-MSH-003-front.jpg"),
        new ProductSummary("CM-MSH-004", "Pure Linen Relaxed Resort Shirt", "Zara", "Shirts", "Amazon", new BigDecimal("1899"), new BigDecimal("2990"), 4.5, true, "/products/shirts/CM-MSH-004-front.jpg"),
        new ProductSummary("CM-MSH-005", "Slim Fit Micro-Print Cotton Formal Shirt", "Van Heusen", "Shirts", "Trends", new BigDecimal("1049"), new BigDecimal("1999"), 4.1, true, "/products/shirts/CM-MSH-005-front.jpg"),
        new ProductSummary("CM-MSH-006", "Mandarin Collar Textured Cotton Shirt", "FabIndia", "Shirts", "Myntra", new BigDecimal("1399"), new BigDecimal("1899"), 4.6, true, "/products/shirts/CM-MSH-006-front.jpg"),
        new ProductSummary("CM-MSH-007", "Cuban Collar Tropical Printed Shirt", "H&M", "Shirts", "AJIO", new BigDecimal("799"), new BigDecimal("1499"), 4.3, true, "/products/shirts/CM-MSH-007-front.jpg"),
        new ProductSummary("CM-MSH-008", "Checked Heavy Cotton Overshirt", "Jack & Jones", "Shirts", "Amazon", new BigDecimal("1599"), new BigDecimal("3299"), 4.4, false, "/products/shirts/CM-MSH-008-front.jpg"),
        new ProductSummary("CM-MTS-001", "Heavyweight Boxy Drop-Shoulder T-Shirt", "Souled Store", "T-Shirts", "Myntra", new BigDecimal("699"), new BigDecimal("1299"), 4.5, true, "/products/t-shirts/CM-MTS-001-front.jpg"),
        new ProductSummary("CM-MTS-002", "Classic Pima Cotton Crew Neck Tee", "Marks & Spencer", "T-Shirts", "AJIO", new BigDecimal("849"), new BigDecimal("1499"), 4.6, true, "/products/t-shirts/CM-MTS-002-front.jpg"),
        new ProductSummary("CM-MTS-003", "Graphic Vintage Typography T-Shirt", "Roadster", "T-Shirts", "Flipkart", new BigDecimal("399"), new BigDecimal("999"), 4.1, true, "/products/t-shirts/CM-MTS-003-front.jpg"),
        new ProductSummary("CM-MTS-004", "Solid Pique Cotton Polo T-Shirt", "U.S. Polo Assn.", "T-Shirts", "Amazon", new BigDecimal("999"), new BigDecimal("1899"), 4.3, true, "/products/t-shirts/CM-MTS-004-front.jpg"),
        new ProductSummary("CM-MTS-005", "Acid Wash Street Culture Oversized Tee", "Bewakoof", "T-Shirts", "Meesho", new BigDecimal("499"), new BigDecimal("1199"), 4.2, true, "/products/t-shirts/CM-MTS-005-front.jpg"),
        new ProductSummary("CM-MTS-006", "Dri-FIT Breathable Training T-Shirt", "Nike", "T-Shirts", "Nike", new BigDecimal("1495"), new BigDecimal("1995"), 4.7, true, "/products/t-shirts/CM-MTS-006-front.jpg"),
        new ProductSummary("CM-MTS-007", "Striped Nautical Crew Neck T-Shirt", "Trends", "T-Shirts", "Trends", new BigDecimal("449"), new BigDecimal("899"), 4, true, "/products/t-shirts/CM-MTS-007-front.jpg"),
        new ProductSummary("CM-MTS-008", "Waffle Knit Thermal Raglan Tee", "H&M", "T-Shirts", "Myntra", new BigDecimal("899"), new BigDecimal("1499"), 4.3, false, "/products/t-shirts/CM-MTS-008-front.jpg"),
        new ProductSummary("CM-MJN-001", "511 Slim Fit Stretch Denim Jeans", "Levi's", "Jeans", "Amazon", new BigDecimal("1999"), new BigDecimal("3999"), 4.5, true, "/products/jeans/CM-MJN-001-front.jpg"),
        new ProductSummary("CM-MJN-002", "Vintage Loose Fit Baggy Skater Jeans", "Spykar", "Jeans", "Flipkart", new BigDecimal("1299"), new BigDecimal("2899"), 4.3, true, "/products/jeans/CM-MJN-002-front.jpg"),
        new ProductSummary("CM-MJN-003", "Tapered Fit Clean Black Stretch Jeans", "Wrangler", "Jeans", "AJIO", new BigDecimal("1499"), new BigDecimal("2999"), 4.4, true, "/products/jeans/CM-MJN-003-front.jpg"),
        new ProductSummary("CM-MJN-004", "Mid-Rise Distressed Knee Cut Jeans", "Flying Machine", "Jeans", "Myntra", new BigDecimal("1149"), new BigDecimal("2499"), 4.2, true, "/products/jeans/CM-MJN-004-front.jpg"),
        new ProductSummary("CM-MJN-005", "Classic Straight Leg Raw Denim Jeans", "Lee", "Jeans", "Trends", new BigDecimal("1399"), new BigDecimal("2799"), 4.4, true, "/products/jeans/CM-MJN-005-front.jpg"),
        new ProductSummary("CM-MJN-006", "Comfort Relaxed Fit Stretch Denim", "Peter England", "Jeans", "Meesho", new BigDecimal("799"), new BigDecimal("1699"), 4, true, "/products/jeans/CM-MJN-006-front.jpg"),
        new ProductSummary("CM-MJN-007", "Selvedge Heritage Indigo Denim Jeans", "Jack & Jones", "Jeans", "AJIO", new BigDecimal("2499"), new BigDecimal("4999"), 4.6, false, "/products/jeans/CM-MJN-007-front.jpg"),
        new ProductSummary("CM-MTR-001", "Slim Fit Stretch Twill Chino Trousers", "Blackberrys", "Trousers", "Myntra", new BigDecimal("1399"), new BigDecimal("2799"), 4.4, true, "/products/trousers/CM-MTR-001-front.jpg"),
        new ProductSummary("CM-MTR-002", "Multi-Pocket Tactical Cargo Pants", "Roadster", "Trousers", "AJIO", new BigDecimal("1099"), new BigDecimal("2299"), 4.3, true, "/products/trousers/CM-MTR-002-front.jpg"),
        new ProductSummary("CM-MTR-003", "Formal Flat Front Poly-Viscose Trousers", "Raymond", "Trousers", "Amazon", new BigDecimal("1499"), new BigDecimal("2499"), 4.5, true, "/products/trousers/CM-MTR-003-front.jpg"),
        new ProductSummary("CM-MTR-004", "Pleated Relaxed Linen-Blend Trousers", "Zara", "Trousers", "Trends", new BigDecimal("1799"), new BigDecimal("3290"), 4.2, true, "/products/trousers/CM-MTR-004-front.jpg"),
        new ProductSummary("CM-MTR-005", "Everyday Stretch Cotton Tapered Trousers", "John Players", "Trousers", "Flipkart", new BigDecimal("799"), new BigDecimal("1799"), 4.1, true, "/products/trousers/CM-MTR-005-front.jpg"),
        new ProductSummary("CM-MTR-006", "Drawstring Elastic Waist Commuter Pants", "H&M", "Trousers", "Myntra", new BigDecimal("999"), new BigDecimal("1999"), 4.3, false, "/products/trousers/CM-MTR-006-front.jpg"),
        new ProductSummary("CM-MJK-001", "Faux Leather Asymmetrical Biker Jacket", "Roadster", "Jackets", "Myntra", new BigDecimal("2199"), new BigDecimal("4999"), 4.4, true, "/products/jackets/CM-MJK-001-front.jpg"),
        new ProductSummary("CM-MJK-002", "Sherpa Lined Vintage Trucker Denim Jacket", "Levi's", "Jackets", "Amazon", new BigDecimal("3499"), new BigDecimal("6999"), 4.7, true, "/products/jackets/CM-MJK-002-front.jpg"),
        new ProductSummary("CM-MJK-003", "Classic Flight Bomber Jacket", "Zara", "Jackets", "AJIO", new BigDecimal("1999"), new BigDecimal("3990"), 4.3, true, "/products/jackets/CM-MJK-003-front.jpg"),
        new ProductSummary("CM-MJK-004", "Lightweight Quilted Puffer Winter Jacket", "Wildcraft", "Jackets", "Flipkart", new BigDecimal("1699"), new BigDecimal("3499"), 4.5, true, "/products/jackets/CM-MJK-004-front.jpg"),
        new ProductSummary("CM-MJK-005", "Hooded Windbreaker Training Track Jacket", "Nike", "Jackets", "Nike", new BigDecimal("2995"), new BigDecimal("4295"), 4.6, true, "/products/jackets/CM-MJK-005-front.jpg"),
        new ProductSummary("CM-MJK-006", "Single-Breasted Casual Knit Blazer Jacket", "Allen Solly", "Jackets", "Trends", new BigDecimal("2499"), new BigDecimal("5499"), 4.2, false, "/products/jackets/CM-MJK-006-front.jpg"),
        new ProductSummary("CM-MHD-001", "Essential Heavyweight Oversized Hoodie", "H&M", "Hoodies", "Myntra", new BigDecimal("1299"), new BigDecimal("2499"), 4.2, true, "/products/hoodies/CM-MHD-001-front.jpg"),
        new ProductSummary("CM-MHD-002", "Club Fleece Sport Pullover Hoodie", "Nike", "Hoodies", "Nike", new BigDecimal("2495"), new BigDecimal("3695"), 4.6, true, "/products/hoodies/CM-MHD-002-front.jpg"),
        new ProductSummary("CM-MHD-003", "Full-Zip French Terry Athletic Hoodie", "Puma", "Hoodies", "Amazon", new BigDecimal("1599"), new BigDecimal("3299"), 4.3, true, "/products/hoodies/CM-MHD-003-front.jpg"),
        new ProductSummary("CM-MHD-004", "Streetwear Acid Wash Graphic Print Hoodie", "Souled Store", "Hoodies", "AJIO", new BigDecimal("1199"), new BigDecimal("2199"), 4.4, true, "/products/hoodies/CM-MHD-004-front.jpg"),
        new ProductSummary("CM-MHD-005", "Colorblocked Casual Fleece Sweatshirt Hoodie", "Roadster", "Hoodies", "Flipkart", new BigDecimal("799"), new BigDecimal("1999"), 4.1, true, "/products/hoodies/CM-MHD-005-front.jpg"),
        new ProductSummary("CM-MHD-006", "Thermal Polar Fleece Quarter-Zip Hoodie", "Quechua", "Hoodies", "Trends", new BigDecimal("999"), new BigDecimal("1799"), 4.5, false, "/products/hoodies/CM-MHD-006-front.jpg"),
        new ProductSummary("CM-WDR-001", "Floral Tiered Bohemian Maxi Dress", "Zara", "Dresses", "Myntra", new BigDecimal("1899"), new BigDecimal("3590"), 4.5, true, "/products/dresses/CM-WDR-001-front.jpg"),
        new ProductSummary("CM-WDR-002", "V-Neck Satin Slip Cocktail Dress", "Mango", "Dresses", "AJIO", new BigDecimal("2299"), new BigDecimal("4590"), 4.6, true, "/products/dresses/CM-WDR-002-front.jpg"),
        new ProductSummary("CM-WDR-003", "A-Line Cotton Shirt Dress with Belt", "Marks & Spencer", "Dresses", "Amazon", new BigDecimal("1699"), new BigDecimal("2999"), 4.3, true, "/products/dresses/CM-WDR-003-front.jpg"),
        new ProductSummary("CM-WDR-004", "Ribbed Knit Bodycon Midi Dress", "Forever 21", "Dresses", "Flipkart", new BigDecimal("899"), new BigDecimal("1999"), 4.2, true, "/products/dresses/CM-WDR-004-front.jpg"),
        new ProductSummary("CM-WDR-005", "Fit & Flare Polka Dot Summer Dress", "Tokyo Talkies", "Dresses", "Meesho", new BigDecimal("549"), new BigDecimal("1299"), 4.1, true, "/products/dresses/CM-WDR-005-front.jpg"),
        new ProductSummary("CM-WDR-006", "Embroidered Broderie Anglaise Midi Dress", "H&M", "Dresses", "Trends", new BigDecimal("1799"), new BigDecimal("2999"), 4.4, true, "/products/dresses/CM-WDR-006-front.jpg"),
        new ProductSummary("CM-WDR-007", "Wrap Style Floral Georgette Ruffle Dress", "Vero Moda", "Dresses", "Myntra", new BigDecimal("1499"), new BigDecimal("2999"), 4.5, true, "/products/dresses/CM-WDR-007-front.jpg"),
        new ProductSummary("CM-WDR-008", "Smocked Bodice Linen Mini Dress", "Only", "Dresses", "AJIO", new BigDecimal("1199"), new BigDecimal("2499"), 4.2, false, "/products/dresses/CM-WDR-008-front.jpg"),
        new ProductSummary("CM-WTP-001", "Floral Printed Peplum Wrap Top", "Vero Moda", "Tops", "Myntra", new BigDecimal("799"), new BigDecimal("1799"), 4.3, true, "/products/tops/CM-WTP-001-front.jpg"),
        new ProductSummary("CM-WTP-002", "Ribbed Square-Neck Fitted Knit Crop Top", "H&M", "Tops", "AJIO", new BigDecimal("499"), new BigDecimal("999"), 4.4, true, "/products/tops/CM-WTP-002-front.jpg"),
        new ProductSummary("CM-WTP-003", "Puff Sleeve Swiss Dot Chiffon Blouse", "Forever New", "Tops", "Amazon", new BigDecimal("1399"), new BigDecimal("2600"), 4.5, true, "/products/tops/CM-WTP-003-front.jpg"),
        new ProductSummary("CM-WTP-004", "Button-Down Broderie Cotton Peasant Top", "Zara", "Tops", "Trends", new BigDecimal("1199"), new BigDecimal("2290"), 4.2, true, "/products/tops/CM-WTP-004-front.jpg"),
        new ProductSummary("CM-WTP-005", "Graphic Casual Cotton Boxy Tee", "Ginger", "Tops", "Trends", new BigDecimal("399"), new BigDecimal("799"), 4.1, true, "/products/tops/CM-WTP-005-front.jpg"),
        new ProductSummary("CM-WTP-006", "Satin Cowl-Neck Camisole Evening Top", "Urbanic", "Tops", "Meesho", new BigDecimal("449"), new BigDecimal("1199"), 4, true, "/products/tops/CM-WTP-006-front.jpg"),
        new ProductSummary("CM-WTP-007", "Smocked Ruffled Off-Shoulder Bardot Top", "Athena", "Tops", "Flipkart", new BigDecimal("649"), new BigDecimal("1499"), 4.3, false, "/products/tops/CM-WTP-007-front.jpg"),
        new ProductSummary("CM-WJN-001", "High-Rise Wide-Leg Flare Denim Jeans", "Levi's", "Women's Jeans", "Amazon", new BigDecimal("1899"), new BigDecimal("3899"), 4.6, true, "/products/women-jeans/CM-WJN-001-front.jpg"),
        new ProductSummary("CM-WJN-002", "Ankle-Length Vintage Mom Fit Jeans", "H&M", "Women's Jeans", "Myntra", new BigDecimal("1499"), new BigDecimal("2499"), 4.4, true, "/products/women-jeans/CM-WJN-002-front.jpg"),
        new ProductSummary("CM-WJN-003", "Super Skinny Sculpt High-Waist Jeans", "Only", "Women's Jeans", "AJIO", new BigDecimal("1299"), new BigDecimal("2799"), 4.3, true, "/products/women-jeans/CM-WJN-003-front.jpg"),
        new ProductSummary("CM-WJN-004", "Straight Fit Slit Hem Fashion Jeans", "Zara", "Women's Jeans", "Trends", new BigDecimal("1699"), new BigDecimal("3290"), 4.5, true, "/products/women-jeans/CM-WJN-004-front.jpg"),
        new ProductSummary("CM-WJN-005", "Distressed Knee Cut Boyfriend Jeans", "Kraus Jeans", "Women's Jeans", "Flipkart", new BigDecimal("999"), new BigDecimal("2299"), 4.1, true, "/products/women-jeans/CM-WJN-005-front.jpg"),
        new ProductSummary("CM-WJN-006", "Paperbag Waist Belted Denim Trousers", "Tokyo Talkies", "Women's Jeans", "Meesho", new BigDecimal("699"), new BigDecimal("1599"), 4.2, false, "/products/women-jeans/CM-WJN-006-front.jpg"),
        new ProductSummary("CM-WKT-001", "Indigo Block Print Straight Cotton Kurti", "Anouk", "Kurtis", "Flipkart", new BigDecimal("749"), new BigDecimal("1499"), 4.5, true, "/products/kurtis/CM-WKT-001-front.jpg"),
        new ProductSummary("CM-WKT-002", "Flared Anarkali Chanderi Silk Kurti", "Biba", "Kurtis", "Myntra", new BigDecimal("1799"), new BigDecimal("3599"), 4.6, true, "/products/kurtis/CM-WKT-002-front.jpg"),
        new ProductSummary("CM-WKT-003", "Embroidered Chikankari Handcrafted Kurti", "Ada Lucknow", "Kurtis", "Amazon", new BigDecimal("1299"), new BigDecimal("2499"), 4.7, true, "/products/kurtis/CM-WKT-003-front.jpg"),
        new ProductSummary("CM-WKT-004", "A-Line Floral Print Tunic Kurti", "W for Woman", "Kurtis", "AJIO", new BigDecimal("999"), new BigDecimal("1999"), 4.3, true, "/products/kurtis/CM-WKT-004-front.jpg"),
        new ProductSummary("CM-WKT-005", "Bandhani Print Rayon Flared Kurti", "Jaipur Kurti", "Kurtis", "Meesho", new BigDecimal("499"), new BigDecimal("1299"), 4.2, true, "/products/kurtis/CM-WKT-005-front.jpg"),
        new ProductSummary("CM-WKT-006", "Khadi Cotton Casual Everyday Kurti", "FabIndia", "Kurtis", "Trends", new BigDecimal("1199"), new BigDecimal("1890"), 4.4, true, "/products/kurtis/CM-WKT-006-front.jpg"),
        new ProductSummary("CM-WKT-007", "Mirror Work Festive Rayon Kurti", "Aurelia", "Kurtis", "Myntra", new BigDecimal("899"), new BigDecimal("1799"), 4.3, true, "/products/kurtis/CM-WKT-007-front.jpg"),
        new ProductSummary("CM-WKT-008", "Layered Angrakha Style Ethnic Kurti", "Libas", "Kurtis", "Flipkart", new BigDecimal("949"), new BigDecimal("2199"), 4.4, false, "/products/kurtis/CM-WKT-008-front.jpg"),
        new ProductSummary("CM-WET-001", "Banarasi Silk Jacquard Woven Saree", "Kalamandir", "Ethnic Wear", "Myntra", new BigDecimal("2499"), new BigDecimal("5999"), 4.6, true, "/products/ethnic-wear/CM-WET-001-front.jpg"),
        new ProductSummary("CM-WET-002", "Sequined Semi-Stitched Net Lehenga Choli", "Chhabra 555", "Ethnic Wear", "Amazon", new BigDecimal("3499"), new BigDecimal("8999"), 4.5, true, "/products/ethnic-wear/CM-WET-002-front.jpg"),
        new ProductSummary("CM-WET-003", "Embroidered Kurta with Palazzo & Dupatta Set", "Biba", "Ethnic Wear", "AJIO", new BigDecimal("2199"), new BigDecimal("4299"), 4.4, true, "/products/ethnic-wear/CM-WET-003-front.jpg"),
        new ProductSummary("CM-WET-004", "Pure Handloom Kanjeevaram Silk Saree", "Pothys", "Ethnic Wear", "Trends", new BigDecimal("3999"), new BigDecimal("7999"), 4.7, true, "/products/ethnic-wear/CM-WET-004-front.jpg"),
        new ProductSummary("CM-WET-005", "Printed Cotton Sharara Suit Set", "Aasiya", "Ethnic Wear", "Flipkart", new BigDecimal("1199"), new BigDecimal("2799"), 4.2, true, "/products/ethnic-wear/CM-WET-005-front.jpg"),
        new ProductSummary("CM-WET-006", "Floral Printed Ready-to-Wear Georgette Saree", "Saree Swarg", "Ethnic Wear", "Meesho", new BigDecimal("699"), new BigDecimal("1999"), 4.1, false, "/products/ethnic-wear/CM-WET-006-front.jpg"),
        new ProductSummary("CM-WJK-001", "Double-Breasted Classic Belted Trench Coat", "Mango", "Women's Jackets", "Myntra", new BigDecimal("3299"), new BigDecimal("6990"), 4.7, true, "/products/women-jackets/CM-WJK-001-front.jpg"),
        new ProductSummary("CM-WJK-002", "Cropped Moto Faux Leather Biker Jacket", "Zara", "Women's Jackets", "AJIO", new BigDecimal("2499"), new BigDecimal("4590"), 4.5, true, "/products/women-jackets/CM-WJK-002-front.jpg"),
        new ProductSummary("CM-WJK-003", "Oversized Drop-Shoulder Denim Jacket", "Levi's", "Women's Jackets", "Amazon", new BigDecimal("2199"), new BigDecimal("4299"), 4.4, true, "/products/women-jackets/CM-WJK-003-front.jpg"),
        new ProductSummary("CM-WJK-004", "Short Padded Puffer Winter Jacket with Hood", "H&M", "Women's Jackets", "Trends", new BigDecimal("1799"), new BigDecimal("3499"), 4.3, true, "/products/women-jackets/CM-WJK-004-front.jpg"),
        new ProductSummary("CM-WJK-005", "Tailored Open-Front Formal Work Blazer", "Van Heusen", "Women's Jackets", "Flipkart", new BigDecimal("1699"), new BigDecimal("3499"), 4.4, true, "/products/women-jackets/CM-WJK-005-front.jpg"),
        new ProductSummary("CM-WJK-006", "Faux Shearling Teddy Fleece Zip Jacket", "Forever 21", "Women's Jackets", "Meesho", new BigDecimal("999"), new BigDecimal("2299"), 4.2, false, "/products/women-jackets/CM-WJK-006-front.jpg"),
        new ProductSummary("CM-KID-001", "Boys Pure Cotton Graphic T-Shirt & Shorts Set", "Mothercare", "Kids Wear", "Myntra", new BigDecimal("699"), new BigDecimal("1499"), 4.5, true, "/products/kids-wear/CM-KID-001-front.jpg"),
        new ProductSummary("CM-KID-002", "Girls Floral Tiered Cotton Summer Frock", "Gini & Jony", "Kids Wear", "Amazon", new BigDecimal("799"), new BigDecimal("1699"), 4.6, true, "/products/kids-wear/CM-KID-002-front.jpg"),
        new ProductSummary("CM-KID-003", "Unisex Denim Dungarees with Striped Inner Tee", "H&M", "Kids Wear", "AJIO", new BigDecimal("1199"), new BigDecimal("2299"), 4.4, true, "/products/kids-wear/CM-KID-003-front.jpg"),
        new ProductSummary("CM-KID-004", "Boys Hooded Lightweight Padded Winter Vest", "U.S. Polo Assn. Kids", "Kids Wear", "Trends", new BigDecimal("899"), new BigDecimal("1899"), 4.3, true, "/products/kids-wear/CM-KID-004-front.jpg"),
        new ProductSummary("CM-KID-005", "Girls Sparkle Tulle Birthday Party Dress", "Hopscotch", "Kids Wear", "Flipkart", new BigDecimal("1049"), new BigDecimal("2499"), 4.5, true, "/products/kids-wear/CM-KID-005-front.jpg"),
        new ProductSummary("CM-KID-006", "Toddlers Organic Cotton Printed Sleepsuit 2-Pack", "FirstCry", "Kids Wear", "Meesho", new BigDecimal("499"), new BigDecimal("1199"), 4.2, true, "/products/kids-wear/CM-KID-006-front.jpg"),
        new ProductSummary("CM-KID-007", "Boys Cotton Chino Pants with Suspenders", "Marks & Spencer Kids", "Kids Wear", "AJIO", new BigDecimal("949"), new BigDecimal("1999"), 4.4, false, "/products/kids-wear/CM-KID-007-front.jpg"),
        new ProductSummary("CM-SNK-001", "Air Max Retro Low Lifestyle Sneakers", "Nike", "Sneakers", "Nike", new BigDecimal("4495"), new BigDecimal("6495"), 4.8, true, "/products/sneakers/CM-SNK-001-front.jpg"),
        new ProductSummary("CM-SNK-002", "Classic Canvas Everyday Low-Top Sneakers", "Puma", "Sneakers", "Meesho", new BigDecimal("1399"), new BigDecimal("2999"), 4.1, true, "/products/sneakers/CM-SNK-002-front.jpg"),
        new ProductSummary("CM-SNK-003", "Grand Court Cloudfoam Leather Tennis Sneakers", "Adidas", "Sneakers", "Myntra", new BigDecimal("2699"), new BigDecimal("5599"), 4.5, true, "/products/sneakers/CM-SNK-003-front.jpg"),
        new ProductSummary("CM-SNK-004", "574 Core Heritage Suede Running Sneakers", "New Balance", "Sneakers", "Amazon", new BigDecimal("3999"), new BigDecimal("7999"), 4.7, true, "/products/sneakers/CM-SNK-004-front.jpg"),
        new ProductSummary("CM-SNK-005", "Chuck 70 High-Top Vintage Canvas Sneakers", "Converse", "Sneakers", "AJIO", new BigDecimal("2999"), new BigDecimal("4999"), 4.6, true, "/products/sneakers/CM-SNK-005-front.jpg"),
        new ProductSummary("CM-SNK-006", "Old Skool Suede Stripe Skate Sneakers", "Vans", "Sneakers", "Flipkart", new BigDecimal("2399"), new BigDecimal("4499"), 4.5, true, "/products/sneakers/CM-SNK-006-front.jpg"),
        new ProductSummary("CM-SNK-007", "Slip-On Chunky Knit Walking Sneakers", "Red Tape", "Sneakers", "Trends", new BigDecimal("1199"), new BigDecimal("3899"), 4.2, true, "/products/sneakers/CM-SNK-007-front.jpg"),
        new ProductSummary("CM-SNK-008", "Rebound Joy High-Top Basketball Sneakers", "Puma", "Sneakers", "AJIO", new BigDecimal("2799"), new BigDecimal("5499"), 4.4, false, "/products/sneakers/CM-SNK-008-front.jpg"),
        new ProductSummary("CM-CSH-001", "Genuine Leather Handcrafted Oxford Brogues", "Bata", "Shoes", "Amazon", new BigDecimal("1899"), new BigDecimal("3499"), 4.4, true, "/products/shoes/CM-CSH-001-front.jpg"),
        new ProductSummary("CM-CSH-002", "Suede Penny Loafers with Moccasin Stitching", "Hush Puppies", "Shoes", "Myntra", new BigDecimal("2499"), new BigDecimal("4999"), 4.6, true, "/products/shoes/CM-CSH-002-front.jpg"),
        new ProductSummary("CM-CSH-003", "Classic Chelsea Leather Ankle Boots", "Red Chief", "Shoes", "Flipkart", new BigDecimal("2299"), new BigDecimal("4899"), 4.3, true, "/products/shoes/CM-CSH-003-front.jpg"),
        new ProductSummary("CM-CSH-004", "Breathable Canvas Espadrilles Slip-Ons", "Soludos", "Shoes", "AJIO", new BigDecimal("999"), new BigDecimal("1999"), 4.2, true, "/products/shoes/CM-CSH-004-front.jpg"),
        new ProductSummary("CM-CSH-005", "Formal Slip-On Derby Shoes with Elastic Gusset", "Woodland", "Shoes", "Trends", new BigDecimal("1799"), new BigDecimal("3295"), 4.4, true, "/products/shoes/CM-CSH-005-front.jpg"),
        new ProductSummary("CM-CSH-006", "Casual Driving Shoes with Metal Bit Buckle", "Carlton London", "Shoes", "Meesho", new BigDecimal("849"), new BigDecimal("1999"), 4, false, "/products/shoes/CM-CSH-006-front.jpg"),
        new ProductSummary("CM-SPT-001", "Dri-FIT Moisture-Wicking Training Shorts", "Nike", "Sportswear", "Nike", new BigDecimal("1495"), new BigDecimal("2195"), 4.7, true, "/products/sportswear/CM-SPT-001-front.jpg"),
        new ProductSummary("CM-SPT-002", "Tiro 23 Tapered Soccer Track Pants", "Adidas", "Sportswear", "Myntra", new BigDecimal("1899"), new BigDecimal("3599"), 4.6, true, "/products/sportswear/CM-SPT-002-front.jpg"),
        new ProductSummary("CM-SPT-003", "Seamless High-Waist Workout Leggings", "Puma", "Sportswear", "Amazon", new BigDecimal("1299"), new BigDecimal("2799"), 4.5, true, "/products/sportswear/CM-SPT-003-front.jpg"),
        new ProductSummary("CM-SPT-004", "High-Support Zip-Front Sports Bra", "Decathlon", "Sportswear", "AJIO", new BigDecimal("899"), new BigDecimal("1799"), 4.4, true, "/products/sportswear/CM-SPT-004-front.jpg"),
        new ProductSummary("CM-SPT-005", "Active Quarter-Zip Thermal Running Pullover", "Under Armour", "Sportswear", "Flipkart", new BigDecimal("1599"), new BigDecimal("2999"), 4.5, true, "/products/sportswear/CM-SPT-005-front.jpg"),
        new ProductSummary("CM-SPT-006", "Relaxed Fit Cotton French Terry Joggers", "Performax", "Sportswear", "Trends", new BigDecimal("799"), new BigDecimal("1499"), 4.2, true, "/products/sportswear/CM-SPT-006-front.jpg"),
        new ProductSummary("CM-SPT-007", "Quick-Dry Anti-Odor Gym Stringer Vest", "HRX by Hrithik Roshan", "Sportswear", "Meesho", new BigDecimal("349"), new BigDecimal("899"), 4.1, false, "/products/sportswear/CM-SPT-007-front.jpg")
    );

    @Override
    public String platform() {
        return "DEMO";
    }

    @Override
    public List<ProductSummary> search(String query) {
        if (query == null || query.isBlank()) return PRODUCTS;
        String needle = query.toLowerCase();
        return PRODUCTS.stream()
            .filter(product -> (product.title() + " " + product.brand() + " " + product.category()).toLowerCase().contains(needle))
            .toList();
    }
}
