// Catalogue Definition with 110 products across 16 fashion categories and 7 platforms
export const rawProducts = [
  // ==========================================
  // 1. MEN'S SHIRTS (8 items)
  // ==========================================
  {
    id: "CM-MSH-001",
    title: "Oversized Black Denim Casual Shirt",
    brand: "Roadster",
    category: "Shirts",
    subcategory: "Casual Shirts",
    gender: "Men",
    platform: "AJIO",
    price: 899,
    originalPrice: 1799,
    rating: 4.4,
    reviews: 1240,
    colors: ["Black", "Washed Charcoal"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    available: true,
    description: "Relaxed-fit washed black denim shirt featuring twin flap pockets, drop shoulders, and buttoned cuffs. Ideal for streetwear layering.",
    priceHistory: [1199, 1099, 1099, 999, 949, 899],
    folder: "shirts",
    photoId: "1598032895397-b9472444bf93"
  },
  {
    id: "CM-MSH-002",
    title: "Classic Oxford Cotton Button-Down Shirt",
    brand: "Allen Solly",
    category: "Shirts",
    subcategory: "Formal Shirts",
    gender: "Men",
    platform: "Myntra",
    price: 1199,
    originalPrice: 2199,
    rating: 4.3,
    reviews: 870,
    colors: ["Light Blue", "Classic White"],
    sizes: ["38", "40", "42", "44"],
    available: true,
    description: "Tailored slim-fit formal shirt crafted in pure breathable Oxford cotton with button-down collar and curved hemline.",
    priceHistory: [1499, 1399, 1299, 1299, 1199, 1199],
    folder: "shirts",
    photoId: "1602810318383-e386cc2a3ccf"
  },
  {
    id: "CM-MSH-003",
    title: "Vintage Plaid Flannel Casual Shirt",
    brand: "Highlander",
    category: "Shirts",
    subcategory: "Casual Shirts",
    gender: "Men",
    platform: "Flipkart",
    price: 649,
    originalPrice: 1599,
    rating: 4.2,
    reviews: 2150,
    colors: ["Red Plaid", "Forest Green Plaid"],
    sizes: ["M", "L", "XL"],
    available: true,
    description: "Brushed heavyweight cotton flannel shirt with buffalo check pattern, warm texture, and casual spread collar.",
    priceHistory: [899, 799, 749, 699, 649, 649],
    folder: "shirts",
    photoId: "1596755094514-f87e34085b2c"
  },
  {
    id: "CM-MSH-004",
    title: "Pure Linen Relaxed Resort Shirt",
    brand: "Zara",
    category: "Shirts",
    subcategory: "Resort Shirts",
    gender: "Men",
    platform: "Amazon",
    price: 1899,
    originalPrice: 2990,
    rating: 4.5,
    reviews: 640,
    colors: ["Beige", "Olive", "White"],
    sizes: ["S", "M", "L", "XL"],
    available: true,
    description: "Breezy French linen shirt with camp collar, short sleeves, and relaxed silhouette. Built for sunny getaways and summer lounging.",
    priceHistory: [2490, 2290, 2090, 1990, 1899, 1899],
    folder: "shirts",
    photoId: "1607345366928-199ea26cfe3e"
  },
  {
    id: "CM-MSH-005",
    title: "Slim Fit Micro-Print Cotton Formal Shirt",
    brand: "Van Heusen",
    category: "Shirts",
    subcategory: "Formal Shirts",
    gender: "Men",
    platform: "Trends",
    price: 1049,
    originalPrice: 1999,
    rating: 4.1,
    reviews: 512,
    colors: ["Navy Blue", "Charcoal"],
    sizes: ["39", "40", "42", "44"],
    available: true,
    description: "Wrinkle-resistant fine cotton formal shirt boasting understated geometric micro-prints and an easy-iron finish.",
    priceHistory: [1399, 1299, 1199, 1149, 1049, 1049],
    folder: "shirts",
    photoId: "1620012253295-c15c429f66bf"
  },
  {
    id: "CM-MSH-006",
    title: "Mandarin Collar Textured Cotton Shirt",
    brand: "FabIndia",
    category: "Shirts",
    subcategory: "Casual Shirts",
    gender: "Men",
    platform: "Myntra",
    price: 1399,
    originalPrice: 1899,
    rating: 4.6,
    reviews: 930,
    colors: ["Earthy Mustard", "Natural Off-White"],
    sizes: ["S", "M", "L", "XL"],
    available: true,
    description: "Slub-cotton casual shirt highlighted by a clean mandarin collar, wooden buttons, and half-placket detailing.",
    priceHistory: [1699, 1599, 1499, 1399, 1399, 1399],
    folder: "shirts",
    photoId: "1603252109303-2751441dd157"
  },
  {
    id: "CM-MSH-007",
    title: "Cuban Collar Tropical Printed Shirt",
    brand: "H&M",
    category: "Shirts",
    subcategory: "Casual Shirts",
    gender: "Men",
    platform: "AJIO",
    price: 799,
    originalPrice: 1499,
    rating: 4.3,
    reviews: 1420,
    colors: ["Sage Botanical", "Navy Floral"],
    sizes: ["XS", "S", "M", "L", "XL"],
    available: true,
    description: "Flowy viscose shirt with an open notched collar, subtle drape, and artistic tropical palm leaf patterns.",
    priceHistory: [1199, 999, 899, 849, 799, 799],
    folder: "shirts",
    photoId: "1598033129183-c4f50c736f10"
  },
  {
    id: "CM-MSH-008",
    title: "Checked Heavy Cotton Overshirt",
    brand: "Jack & Jones",
    category: "Shirts",
    subcategory: "Overshirts",
    gender: "Men",
    platform: "Amazon",
    price: 1599,
    originalPrice: 3299,
    rating: 4.4,
    reviews: 780,
    colors: ["Brown Plaid", "Monochrome Grey"],
    sizes: ["S", "M", "L", "XL"],
    available: false,
    description: "Heavyweight utility overshirt with deep chest pockets, snap closures, and durable twill cotton construction.",
    priceHistory: [2199, 1999, 1899, 1699, 1599, 1599],
    folder: "shirts",
    photoId: "1604072373690-349f2b84cf82"
  },

  // ==========================================
  // 2. MEN'S T-SHIRTS (8 items)
  // ==========================================
  {
    id: "CM-MTS-001",
    title: "Heavyweight Boxy Drop-Shoulder T-Shirt",
    brand: "Souled Store",
    category: "T-Shirts",
    subcategory: "Oversized Tees",
    gender: "Men",
    platform: "Myntra",
    price: 699,
    originalPrice: 1299,
    rating: 4.5,
    reviews: 3100,
    colors: ["Sage Green", "Jet Black", "Off White"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    available: true,
    description: "240 GSM combed cotton oversized streetwear tee with ribbed crew neck, structured boxy silhouette, and minimal branding.",
    priceHistory: [999, 899, 799, 749, 699, 699],
    folder: "t-shirts",
    photoId: "1521572267360-ee0c2909d518"
  },
  {
    id: "CM-MTS-002",
    title: "Classic Pima Cotton Crew Neck Tee",
    brand: "Marks & Spencer",
    category: "T-Shirts",
    subcategory: "Basic Tees",
    gender: "Men",
    platform: "AJIO",
    price: 849,
    originalPrice: 1499,
    rating: 4.6,
    reviews: 980,
    colors: ["Navy Blue", "Heather Grey", "Pure White"],
    sizes: ["S", "M", "L", "XL"],
    available: true,
    description: "Ultra-soft Peruvian Pima cotton tee with natural stretch, color-lock tech, and clean tailored seams.",
    priceHistory: [1199, 1099, 999, 899, 849, 849],
    folder: "t-shirts",
    photoId: "1583743814966-8936f5b7be1a"
  },
  {
    id: "CM-MTS-003",
    title: "Graphic Vintage Typography T-Shirt",
    brand: "Roadster",
    category: "T-Shirts",
    subcategory: "Graphic Tees",
    gender: "Men",
    platform: "Flipkart",
    price: 399,
    originalPrice: 999,
    rating: 4.1,
    reviews: 4200,
    colors: ["Vintage Mustard", "Faded Rust"],
    sizes: ["S", "M", "L", "XL"],
    available: true,
    description: "Bio-washed cotton graphic tee featuring retro California typography print and ribbed collar.",
    priceHistory: [599, 499, 449, 399, 399, 399],
    folder: "t-shirts",
    photoId: "1503342217505-b0a15ec3261c"
  },
  {
    id: "CM-MTS-004",
    title: "Solid Pique Cotton Polo T-Shirt",
    brand: "U.S. Polo Assn.",
    category: "T-Shirts",
    subcategory: "Polo T-Shirts",
    gender: "Men",
    platform: "Amazon",
    price: 999,
    originalPrice: 1899,
    rating: 4.3,
    reviews: 1820,
    colors: ["Crimson Red", "Royal Blue", "Forest Green"],
    sizes: ["M", "L", "XL", "XXL"],
    available: true,
    description: "Classic honeycomb pique polo with signature embroidered crest, ribbed armbands, and 2-button placket.",
    priceHistory: [1399, 1299, 1199, 1099, 999, 999],
    folder: "t-shirts",
    photoId: "1586363104862-3a5e2ab60d99"
  },
  {
    id: "CM-MTS-005",
    title: "Acid Wash Street Culture Oversized Tee",
    brand: "Bewakoof",
    category: "T-Shirts",
    subcategory: "Oversized Tees",
    gender: "Men",
    platform: "Meesho",
    price: 499,
    originalPrice: 1199,
    rating: 4.2,
    reviews: 2650,
    colors: ["Mineral Wash Black", "Dusty Blue"],
    sizes: ["S", "M", "L", "XL"],
    available: true,
    description: "Heavy mineral acid-washed casual tee with raw edge aesthetics and drop-shoulder relaxed cut.",
    priceHistory: [699, 599, 549, 499, 499, 499],
    folder: "t-shirts",
    photoId: "1576566588028-4147f3842f27"
  },
  {
    id: "CM-MTS-006",
    title: "Dri-FIT Breathable Training T-Shirt",
    brand: "Nike",
    category: "T-Shirts",
    subcategory: "Sports Tees",
    gender: "Men",
    platform: "Nike",
    price: 1495,
    originalPrice: 1995,
    rating: 4.7,
    reviews: 1430,
    colors: ["Black / Reflective Silver", "Obsidian"],
    sizes: ["S", "M", "L", "XL"],
    available: true,
    description: "Moisture-wicking athletic tee engineered with sweat-dispersion technology to keep you dry through strenuous gym sets.",
    priceHistory: [1895, 1795, 1695, 1495, 1495, 1495],
    folder: "t-shirts",
    photoId: "1562157873-818bc0726f68"
  },
  {
    id: "CM-MTS-007",
    title: "Striped Nautical Crew Neck T-Shirt",
    brand: "Trends",
    category: "T-Shirts",
    subcategory: "Striped Tees",
    gender: "Men",
    platform: "Trends",
    price: 449,
    originalPrice: 899,
    rating: 4.0,
    reviews: 730,
    colors: ["Navy & White", "Black & Cream"],
    sizes: ["S", "M", "L", "XL"],
    available: true,
    description: "Yarn-dyed horizontal striped cotton tee with comfortable crew neck and regular daily fit.",
    priceHistory: [699, 599, 499, 449, 449, 449],
    folder: "t-shirts",
    photoId: "1523381294911-8d3cead13475"
  },
  {
    id: "CM-MTS-008",
    title: "Waffle Knit Thermal Raglan Tee",
    brand: "H&M",
    category: "T-Shirts",
    subcategory: "Long Sleeve Tees",
    gender: "Men",
    platform: "Myntra",
    price: 899,
    originalPrice: 1499,
    rating: 4.3,
    reviews: 620,
    colors: ["Charcoal", "Oatmeal"],
    sizes: ["S", "M", "L", "XL"],
    available: false,
    description: "Textured honeycomb waffle knit long-sleeve tee with raglan sleeves and ribbed cuffs for cozy layering.",
    priceHistory: [1299, 1199, 999, 899, 899, 899],
    folder: "t-shirts",
    photoId: "1618354691373-d851c5c3a990"
  },

  // ==========================================
  // 3. MEN'S JEANS (7 items)
  // ==========================================
  {
    id: "CM-MJN-001",
    title: "511 Slim Fit Stretch Denim Jeans",
    brand: "Levi's",
    category: "Jeans",
    subcategory: "Slim Jeans",
    gender: "Men",
    platform: "Amazon",
    price: 1999,
    originalPrice: 3999,
    rating: 4.5,
    reviews: 3890,
    colors: ["Dark Indigo", "Light Stone Wash"],
    sizes: ["30", "32", "34", "36"],
    available: true,
    description: "The iconic modern slim cut with room to move. Built with premium stretch denim that holds its shape all day long.",
    priceHistory: [2799, 2499, 2299, 2199, 1999, 1999],
    folder: "jeans",
    photoId: "1542272604-787c3835535d"
  },
  {
    id: "CM-MJN-002",
    title: "Vintage Loose Fit Baggy Skater Jeans",
    brand: "Spykar",
    category: "Jeans",
    subcategory: "Baggy Jeans",
    gender: "Men",
    platform: "Flipkart",
    price: 1299,
    originalPrice: 2899,
    rating: 4.3,
    reviews: 1450,
    colors: ["Vintage Washed Blue", "Dirty Wash Grey"],
    sizes: ["28", "30", "32", "34"],
    available: true,
    description: "90s nostalgic relaxed baggy jeans with a wide-leg profile, mid-rise waist, and vintage fading around the thighs.",
    priceHistory: [1799, 1599, 1499, 1399, 1299, 1299],
    folder: "jeans",
    photoId: "1541099649105-f69ad21f3246"
  },
  {
    id: "CM-MJN-003",
    title: "Tapered Fit Clean Black Stretch Jeans",
    brand: "Wrangler",
    category: "Jeans",
    subcategory: "Tapered Jeans",
    gender: "Men",
    platform: "AJIO",
    price: 1499,
    originalPrice: 2999,
    rating: 4.4,
    reviews: 920,
    colors: ["Pitch Black"],
    sizes: ["30", "32", "34", "36", "38"],
    available: true,
    description: "Deep jet-black sulfur dyed denim that resists color fading. Tapered through the ankle for a clean sneaker drop.",
    priceHistory: [1999, 1799, 1699, 1499, 1499, 1499],
    folder: "jeans",
    photoId: "1604176354204-9268737828e4"
  },
  {
    id: "CM-MJN-004",
    title: "Mid-Rise Distressed Knee Cut Jeans",
    brand: "Flying Machine",
    category: "Jeans",
    subcategory: "Distressed Jeans",
    gender: "Men",
    platform: "Myntra",
    price: 1149,
    originalPrice: 2499,
    rating: 4.2,
    reviews: 1120,
    colors: ["Faded Ice Blue"],
    sizes: ["30", "32", "34"],
    available: true,
    description: "Edgy distressed jeans with handcrafted slash tears at the knees, whiskering details, and frayed pocket trims.",
    priceHistory: [1599, 1399, 1299, 1149, 1149, 1149],
    folder: "jeans",
    photoId: "1576995853123-5a10305d93c0"
  },
  {
    id: "CM-MJN-005",
    title: "Classic Straight Leg Raw Denim Jeans",
    brand: "Lee",
    category: "Jeans",
    subcategory: "Straight Jeans",
    gender: "Men",
    platform: "Trends",
    price: 1399,
    originalPrice: 2799,
    rating: 4.4,
    reviews: 810,
    colors: ["Raw Rigid Navy"],
    sizes: ["30", "32", "34", "36"],
    available: true,
    description: "Authentic unwashed rigid indigo denim jeans that contour and develop unique personal fade patterns over time.",
    priceHistory: [1899, 1699, 1599, 1399, 1399, 1399],
    folder: "jeans",
    photoId: "1582418702059-97ebafb35d09"
  },
  {
    id: "CM-MJN-006",
    title: "Comfort Relaxed Fit Stretch Denim",
    brand: "Peter England",
    category: "Jeans",
    subcategory: "Relaxed Jeans",
    gender: "Men",
    platform: "Meesho",
    price: 799,
    originalPrice: 1699,
    rating: 4.0,
    reviews: 2310,
    colors: ["Medium Wash Indigo"],
    sizes: ["32", "34", "36", "38"],
    available: true,
    description: "Easy-wear everyday denim featuring an elastane blend for flexible bending, walking, and active commutes.",
    priceHistory: [999, 899, 849, 799, 799, 799],
    folder: "jeans",
    photoId: "1560243563-062bfc001d68"
  },
  {
    id: "CM-MJN-007",
    title: "Selvedge Heritage Indigo Denim Jeans",
    brand: "Jack & Jones",
    category: "Jeans",
    subcategory: "Selvedge Jeans",
    gender: "Men",
    platform: "AJIO",
    price: 2499,
    originalPrice: 4999,
    rating: 4.6,
    reviews: 430,
    colors: ["Deep Indigo Selvedge"],
    sizes: ["30", "32", "34"],
    available: false,
    description: "Woven on vintage shuttle looms with red-line selvedge outseam, heavy copper rivets, and a timeless straight silhouette.",
    priceHistory: [3499, 2999, 2799, 2499, 2499, 2499],
    folder: "jeans",
    photoId: "1516257984-b1b4d707412e"
  },

  // ==========================================
  // 4. MEN'S TROUSERS (6 items)
  // ==========================================
  {
    id: "CM-MTR-001",
    title: "Slim Fit Stretch Twill Chino Trousers",
    brand: "Blackberrys",
    category: "Trousers",
    subcategory: "Chinos",
    gender: "Men",
    platform: "Myntra",
    price: 1399,
    originalPrice: 2799,
    rating: 4.4,
    reviews: 1340,
    colors: ["Khaki Tan", "Olive Green", "Charcoal"],
    sizes: ["30", "32", "34", "36"],
    available: true,
    description: "Versatile smart-casual chinos tailored with smooth stretch-cotton twill, clean welt back pockets, and flat-front waist.",
    priceHistory: [1899, 1699, 1499, 1399, 1399, 1399],
    folder: "trousers",
    photoId: "1473966968600-fa801b869a1a"
  },
  {
    id: "CM-MTR-002",
    title: "Multi-Pocket Tactical Cargo Pants",
    brand: "Roadster",
    category: "Trousers",
    subcategory: "Cargo Pants",
    gender: "Men",
    platform: "AJIO",
    price: 1099,
    originalPrice: 2299,
    rating: 4.3,
    reviews: 2190,
    colors: ["Camo Olive", "Stealth Black"],
    sizes: ["S", "M", "L", "XL"],
    available: true,
    description: "Functional streetwear cargo trousers equipped with 6 utility flap pockets, adjustable ankle toggles, and ripstop cotton fabric.",
    priceHistory: [1499, 1349, 1199, 1099, 1099, 1099],
    folder: "trousers",
    photoId: "1624378439575-d8705ad7ae80"
  },
  {
    id: "CM-MTR-003",
    title: "Formal Flat Front Poly-Viscose Trousers",
    brand: "Raymond",
    category: "Trousers",
    subcategory: "Formal Trousers",
    gender: "Men",
    platform: "Amazon",
    price: 1499,
    originalPrice: 2499,
    rating: 4.5,
    reviews: 870,
    colors: ["Steel Grey", "Dark Navy"],
    sizes: ["30", "32", "34", "36", "38"],
    available: true,
    description: "Executive-grade formal trousers featuring crease-retention technology, soft viscose blend, and tailored waistband.",
    priceHistory: [1999, 1799, 1599, 1499, 1499, 1499],
    folder: "trousers",
    photoId: "1594938298603-c8148c4dae35"
  },
  {
    id: "CM-MTR-004",
    title: "Pleated Relaxed Linen-Blend Trousers",
    brand: "Zara",
    category: "Trousers",
    subcategory: "Relaxed Trousers",
    gender: "Men",
    platform: "Trends",
    price: 1799,
    originalPrice: 3290,
    rating: 4.2,
    reviews: 510,
    colors: ["Sand Beige", "Cream"],
    sizes: ["30", "32", "34"],
    available: true,
    description: "Contemporary double-pleated linen trousers offering effortless drape, side slant pockets, and breezy summer charm.",
    priceHistory: [2490, 2190, 1990, 1799, 1799, 1799],
    folder: "trousers",
    photoId: "1509631179647-0177331693ae"
  },
  {
    id: "CM-MTR-005",
    title: "Everyday Stretch Cotton Tapered Trousers",
    brand: "John Players",
    category: "Trousers",
    subcategory: "Casual Trousers",
    gender: "Men",
    platform: "Flipkart",
    price: 799,
    originalPrice: 1799,
    rating: 4.1,
    reviews: 1680,
    colors: ["Coffee Brown", "Slate"],
    sizes: ["30", "32", "34", "36"],
    available: true,
    description: "Budget-friendly durable daily trousers designed with mid-rise waist and versatile tapered leg openings.",
    priceHistory: [1199, 999, 899, 799, 799, 799],
    folder: "trousers",
    photoId: "1506630448388-4e683c67ddb0"
  },
  {
    id: "CM-MTR-006",
    title: "Drawstring Elastic Waist Commuter Pants",
    brand: "H&M",
    category: "Trousers",
    subcategory: "Jogger Trousers",
    gender: "Men",
    platform: "Myntra",
    price: 999,
    originalPrice: 1999,
    rating: 4.3,
    reviews: 940,
    colors: ["Dark Khaki", "Black"],
    sizes: ["S", "M", "L", "XL"],
    available: false,
    description: "Hybrid formal-casual joggers with an internal drawstring waistband, false fly, and cuffed clean hem.",
    priceHistory: [1499, 1299, 1199, 999, 999, 999],
    folder: "trousers",
    photoId: "1552374196-1ab2a1c593e8"
  },

  // ==========================================
  // 5. MEN'S JACKETS (6 items)
  // ==========================================
  {
    id: "CM-MJK-001",
    title: "Faux Leather Asymmetrical Biker Jacket",
    brand: "Roadster",
    category: "Jackets",
    subcategory: "Biker Jackets",
    gender: "Men",
    platform: "Myntra",
    price: 2199,
    originalPrice: 4999,
    rating: 4.4,
    reviews: 1420,
    colors: ["Matte Black"],
    sizes: ["M", "L", "XL"],
    available: true,
    description: "Edgy moto biker jacket tailored with premium PU leather, silver metal zip hardware, notch lapels, and quilted shoulder panels.",
    priceHistory: [3199, 2799, 2499, 2199, 2199, 2199],
    folder: "jackets",
    photoId: "1551028719-00167b16eac5"
  },
  {
    id: "CM-MJK-002",
    title: "Sherpa Lined Vintage Trucker Denim Jacket",
    brand: "Levi's",
    category: "Jackets",
    subcategory: "Denim Jackets",
    gender: "Men",
    platform: "Amazon",
    price: 3499,
    originalPrice: 6999,
    rating: 4.7,
    reviews: 2180,
    colors: ["Stonewash Blue", "Washed Black"],
    sizes: ["S", "M", "L", "XL"],
    available: true,
    description: "Authentic denim trucker jacket insulated with cozy sherpa fleece lining and quilted soft sleeve padding for cold weather warmth.",
    priceHistory: [4999, 4499, 3999, 3499, 3499, 3499],
    folder: "jackets",
    photoId: "1576995853123-5a10305d93c0"
  },
  {
    id: "CM-MJK-003",
    title: "Classic Flight Bomber Jacket",
    brand: "Zara",
    category: "Jackets",
    subcategory: "Bomber Jackets",
    gender: "Men",
    platform: "AJIO",
    price: 1999,
    originalPrice: 3990,
    rating: 4.3,
    reviews: 880,
    colors: ["Military Olive", "Midnight Black"],
    sizes: ["S", "M", "L", "XL"],
    available: true,
    description: "Sleek satin-finish water-resistant bomber jacket featuring ribbed collar, sleeve utility zip pocket, and interior slip pocket.",
    priceHistory: [2990, 2590, 2290, 1999, 1999, 1999],
    folder: "jackets",
    photoId: "1548883354-7622d03aca27"
  },
  {
    id: "CM-MJK-004",
    title: "Lightweight Quilted Puffer Winter Jacket",
    brand: "Wildcraft",
    category: "Jackets",
    subcategory: "Puffer Jackets",
    gender: "Men",
    platform: "Flipkart",
    price: 1699,
    originalPrice: 3499,
    rating: 4.5,
    reviews: 1640,
    colors: ["Cobalt Blue", "Jet Black"],
    sizes: ["M", "L", "XL", "XXL"],
    available: true,
    description: "Feather-light packable puffer jacket filled with thermo-insulation tech and water-repellent micro-ripstop shell.",
    priceHistory: [2499, 2199, 1899, 1699, 1699, 1699],
    folder: "jackets",
    photoId: "1544923246-77307dd654cb"
  },
  {
    id: "CM-MJK-005",
    title: "Hooded Windbreaker Training Track Jacket",
    brand: "Nike",
    category: "Jackets",
    subcategory: "Sport Jackets",
    gender: "Men",
    platform: "Nike",
    price: 2995,
    originalPrice: 4295,
    rating: 4.6,
    reviews: 950,
    colors: ["Black / White Windrunner"],
    sizes: ["S", "M", "L", "XL"],
    available: true,
    description: "Heritage chevron design track jacket engineered with lightweight woven taffeta, mesh vent at the back, and adjustable hood.",
    priceHistory: [3895, 3495, 3295, 2995, 2995, 2995],
    folder: "jackets",
    photoId: "1548883354-9988e0b2a59a"
  },
  {
    id: "CM-MJK-006",
    title: "Single-Breasted Casual Knit Blazer Jacket",
    brand: "Allen Solly",
    category: "Jackets",
    subcategory: "Blazers",
    gender: "Men",
    platform: "Trends",
    price: 2499,
    originalPrice: 5499,
    rating: 4.2,
    reviews: 410,
    colors: ["Navy Heather"],
    sizes: ["38", "40", "42"],
    available: false,
    description: "Unstructured casual blazer in textured poly-cotton knit with patch pockets, two-button closure, and double back vents.",
    priceHistory: [3999, 3499, 2999, 2499, 2499, 2499],
    folder: "jackets",
    photoId: "1507679799987-c73779587ccf"
  },

  // ==========================================
  // 6. MEN'S HOODIES (6 items)
  // ==========================================
  {
    id: "CM-MHD-001",
    title: "Essential Heavyweight Oversized Hoodie",
    brand: "H&M",
    category: "Hoodies",
    subcategory: "Pullover Hoodies",
    gender: "Men",
    platform: "Myntra",
    price: 1299,
    originalPrice: 2499,
    rating: 4.2,
    reviews: 890,
    colors: ["Charcoal", "Cream Oatmeal", "Moss Green"],
    sizes: ["S", "M", "L", "XL"],
    available: true,
    description: "320 GSM heavyweight brushed fleece hoodie engineered for easy, oversized layering with double-layer hood and kangaroo pouch.",
    priceHistory: [1599, 1599, 1499, 1399, 1299, 1299],
    folder: "hoodies",
    photoId: "1556821840-3a63f95609a7"
  },
  {
    id: "CM-MHD-002",
    title: "Club Fleece Sport Pullover Hoodie",
    brand: "Nike",
    category: "Hoodies",
    subcategory: "Sports Hoodies",
    gender: "Men",
    platform: "Nike",
    price: 2495,
    originalPrice: 3695,
    rating: 4.6,
    reviews: 610,
    colors: ["Black", "Heather Grey"],
    sizes: ["S", "M", "L", "XL"],
    available: true,
    description: "A classic fleece hoodie designed for comfort before and after movement, featuring embroidered Swoosh chest branding.",
    priceHistory: [2995, 2795, 2795, 2495, 2495, 2495],
    folder: "hoodies",
    photoId: "1578768079052-aa76e52ff62e"
  },
  {
    id: "CM-MHD-003",
    title: "Full-Zip French Terry Athletic Hoodie",
    brand: "Puma",
    category: "Hoodies",
    subcategory: "Zip Hoodies",
    gender: "Men",
    platform: "Amazon",
    price: 1599,
    originalPrice: 3299,
    rating: 4.3,
    reviews: 1140,
    colors: ["Navy Blue", "Slate Grey"],
    sizes: ["M", "L", "XL", "XXL"],
    available: true,
    description: "Breathable all-season French terry zip-up hoodie with metal zip puller, split kangaroo pocket, and drawcord hood.",
    priceHistory: [2199, 1999, 1799, 1599, 1599, 1599],
    folder: "hoodies",
    photoId: "1509967419530-da38b4704bc6"
  },
  {
    id: "CM-MHD-004",
    title: "Streetwear Acid Wash Graphic Print Hoodie",
    brand: "Souled Store",
    category: "Hoodies",
    subcategory: "Graphic Hoodies",
    gender: "Men",
    platform: "AJIO",
    price: 1199,
    originalPrice: 2199,
    rating: 4.4,
    reviews: 1780,
    colors: ["Vintage Acid Grey", "Midnight Purple"],
    sizes: ["S", "M", "L", "XL"],
    available: true,
    description: "Drop-shoulder relaxed hoodie with anime back print, brushed interior, and ribbed cuffs that retain snug elasticity.",
    priceHistory: [1699, 1499, 1349, 1199, 1199, 1199],
    folder: "hoodies",
    photoId: "1513094735237-8f2714d57c13"
  },
  {
    id: "CM-MHD-005",
    title: "Colorblocked Casual Fleece Sweatshirt Hoodie",
    brand: "Roadster",
    category: "Hoodies",
    subcategory: "Pullover Hoodies",
    gender: "Men",
    platform: "Flipkart",
    price: 799,
    originalPrice: 1999,
    rating: 4.1,
    reviews: 2900,
    colors: ["Maroon & Navy", "Olive & Black"],
    sizes: ["S", "M", "L", "XL"],
    available: true,
    description: "Sporty tricolor colorblocked fleece hoodie offering soft next-to-skin touch and great thermal retention.",
    priceHistory: [1199, 999, 899, 799, 799, 799],
    folder: "hoodies",
    photoId: "1578587018452-892bacefd3f2"
  },
  {
    id: "CM-MHD-006",
    title: "Thermal Polar Fleece Quarter-Zip Hoodie",
    brand: "Quechua",
    category: "Hoodies",
    subcategory: "Fleece Hoodies",
    gender: "Men",
    platform: "Trends",
    price: 999,
    originalPrice: 1799,
    rating: 4.5,
    reviews: 730,
    colors: ["Forest Green", "Earth Brown"],
    sizes: ["M", "L", "XL"],
    available: false,
    description: "Insulating polar fleece pullover hoodie designed for outdoor trails and chilly morning commutes.",
    priceHistory: [1399, 1249, 1099, 999, 999, 999],
    folder: "hoodies",
    photoId: "1543163521-1bf539c55dd2"
  },

  // ==========================================
  // 7. WOMEN'S DRESSES (8 items)
  // ==========================================
  {
    id: "CM-WDR-001",
    title: "Floral Tiered Bohemian Maxi Dress",
    brand: "Zara",
    category: "Dresses",
    subcategory: "Maxi Dresses",
    gender: "Women",
    platform: "Myntra",
    price: 1899,
    originalPrice: 3590,
    rating: 4.5,
    reviews: 1450,
    colors: ["Dusty Pink Floral", "Sage Green Floral"],
    sizes: ["XS", "S", "M", "L"],
    available: true,
    description: "Romantic floral maxi dress designed with ruffled tiered skirt, smocked elastic bodice, and delicate flutter sleeves.",
    priceHistory: [2590, 2290, 2090, 1899, 1899, 1899],
    folder: "dresses",
    photoId: "1595777457583-95e059d581b8"
  },
  {
    id: "CM-WDR-002",
    title: "V-Neck Satin Slip Cocktail Dress",
    brand: "Mango",
    category: "Dresses",
    subcategory: "Slip Dresses",
    gender: "Women",
    platform: "AJIO",
    price: 2299,
    originalPrice: 4590,
    rating: 4.6,
    reviews: 620,
    colors: ["Champagne Gold", "Emerald Green"],
    sizes: ["S", "M", "L"],
    available: true,
    description: "Bias-cut lustrous satin slip dress with adjustable spaghetti straps, draped cowl neckline, and subtle thigh slit.",
    priceHistory: [3290, 2890, 2590, 2299, 2299, 2299],
    folder: "dresses",
    photoId: "1572804013309-59a88b7e92f1"
  },
  {
    id: "CM-WDR-003",
    title: "A-Line Cotton Shirt Dress with Belt",
    brand: "Marks & Spencer",
    category: "Dresses",
    subcategory: "Shirt Dresses",
    gender: "Women",
    platform: "Amazon",
    price: 1699,
    originalPrice: 2999,
    rating: 4.3,
    reviews: 840,
    colors: ["Navy Stripe", "Crisp White"],
    sizes: ["S", "M", "L", "XL"],
    available: true,
    description: "Timeless collared shirt dress made in pure poplin cotton featuring button-through front, roll-up sleeves, and matching fabric belt.",
    priceHistory: [2299, 1999, 1849, 1699, 1699, 1699],
    folder: "dresses",
    photoId: "1515372039744-b8f02a3ae446"
  },
  {
    id: "CM-WDR-004",
    title: "Ribbed Knit Bodycon Midi Dress",
    brand: "Forever 21",
    category: "Dresses",
    subcategory: "Bodycon Dresses",
    gender: "Women",
    platform: "Flipkart",
    price: 899,
    originalPrice: 1999,
    rating: 4.2,
    reviews: 1980,
    colors: ["Terracotta", "Classic Black"],
    sizes: ["XS", "S", "M", "L"],
    available: true,
    description: "Figure-hugging ribbed jersey midi dress with square neck and back walking vent. Versatile styling with boots or sneakers.",
    priceHistory: [1399, 1199, 999, 899, 899, 899],
    folder: "dresses",
    photoId: "1539109136881-3be0616acf4b"
  },
  {
    id: "CM-WDR-005",
    title: "Fit & Flare Polka Dot Summer Dress",
    brand: "Tokyo Talkies",
    category: "Dresses",
    subcategory: "Skater Dresses",
    gender: "Women",
    platform: "Meesho",
    price: 549,
    originalPrice: 1299,
    rating: 4.1,
    reviews: 3200,
    colors: ["Black & White Dots", "Red Dots"],
    sizes: ["S", "M", "L", "XL"],
    available: true,
    description: "Retro-inspired fit and flare dress with sweetheart neckline, short puff sleeves, and flared twirl-friendly hem.",
    priceHistory: [799, 699, 599, 549, 549, 549],
    folder: "dresses",
    photoId: "1496747611176-843222e1e57c"
  },
  {
    id: "CM-WDR-006",
    title: "Embroidered Broderie Anglaise Midi Dress",
    brand: "H&M",
    category: "Dresses",
    subcategory: "Midi Dresses",
    gender: "Women",
    platform: "Trends",
    price: 1799,
    originalPrice: 2999,
    rating: 4.4,
    reviews: 580,
    colors: ["Snow White", "Pastel Yellow"],
    sizes: ["S", "M", "L"],
    available: true,
    description: "Pure cotton midi dress detailed with delicate eyelet embroidery, scalloped hem, and flattering square neck.",
    priceHistory: [2399, 2199, 1999, 1799, 1799, 1799],
    folder: "dresses",
    photoId: "1502716119720-b23a93e5fe1b"
  },
  {
    id: "CM-WDR-007",
    title: "Wrap Style Floral Georgette Ruffle Dress",
    brand: "Vero Moda",
    category: "Dresses",
    subcategory: "Wrap Dresses",
    gender: "Women",
    platform: "Myntra",
    price: 1499,
    originalPrice: 2999,
    rating: 4.5,
    reviews: 1120,
    colors: ["Burgundy Floral"],
    sizes: ["XS", "S", "M", "L"],
    available: true,
    description: "Flattering true wrap silhouette with cascading ruffle trims along the neckline and hem, lined with soft stretch crepe.",
    priceHistory: [2199, 1899, 1699, 1499, 1499, 1499],
    folder: "dresses",
    photoId: "1568252542512-9fe8fe9c87bb"
  },
  {
    id: "CM-WDR-008",
    title: "Smocked Bodice Linen Mini Dress",
    brand: "Only",
    category: "Dresses",
    subcategory: "Mini Dresses",
    gender: "Women",
    platform: "AJIO",
    price: 1199,
    originalPrice: 2499,
    rating: 4.2,
    reviews: 740,
    colors: ["Lilac Purple", "Sage"],
    sizes: ["S", "M", "L"],
    available: false,
    description: "Breathable linen-blend mini dress with all-over smocked stretch bodice, elasticated puff shoulders, and airy flare.",
    priceHistory: [1799, 1599, 1399, 1199, 1199, 1199],
    folder: "dresses",
    photoId: "1585487000160-6ebcfceb0d03"
  },

  // ==========================================
  // 8. WOMEN'S TOPS (7 items)
  // ==========================================
  {
    id: "CM-WTP-001",
    title: "Floral Printed Peplum Wrap Top",
    brand: "Vero Moda",
    category: "Tops",
    subcategory: "Peplum Tops",
    gender: "Women",
    platform: "Myntra",
    price: 799,
    originalPrice: 1799,
    rating: 4.3,
    reviews: 1150,
    colors: ["Blush Pink", "Sky Blue"],
    sizes: ["XS", "S", "M", "L", "XL"],
    available: true,
    description: "Romantic crepe wrap top with self-tie waist belt, flared peplum hem, and subtle bell sleeves.",
    priceHistory: [1199, 1049, 899, 799, 799, 799],
    folder: "tops",
    photoId: "1503342394128-c104d54dba01"
  },
  {
    id: "CM-WTP-002",
    title: "Ribbed Square-Neck Fitted Knit Crop Top",
    brand: "H&M",
    category: "Tops",
    subcategory: "Crop Tops",
    gender: "Women",
    platform: "AJIO",
    price: 499,
    originalPrice: 999,
    rating: 4.4,
    reviews: 2400,
    colors: ["Classic White", "Mocha Brown", "Black"],
    sizes: ["XS", "S", "M", "L"],
    available: true,
    description: "Seamless stretch-rib knit crop top cut with a dramatic square neckline and wide bra-friendly shoulder straps.",
    priceHistory: [799, 699, 599, 499, 499, 499],
    folder: "tops",
    photoId: "1515886657613-9f3515b0c78f"
  },
  {
    id: "CM-WTP-003",
    title: "Puff Sleeve Swiss Dot Chiffon Blouse",
    brand: "Forever New",
    category: "Tops",
    subcategory: "Blouses",
    gender: "Women",
    platform: "Amazon",
    price: 1399,
    originalPrice: 2600,
    rating: 4.5,
    reviews: 580,
    colors: ["Ivory Cream", "Soft Mint"],
    sizes: ["S", "M", "L"],
    available: true,
    description: "Elegant textured Swiss-dot chiffon blouse with voluminous puff sleeves, delicate ruffle collar, and keyhole button back.",
    priceHistory: [1999, 1799, 1599, 1399, 1399, 1399],
    folder: "tops",
    photoId: "1554412933-514a83d2f3c8"
  },
  {
    id: "CM-WTP-004",
    title: "Button-Down Broderie Cotton Peasant Top",
    brand: "Zara",
    category: "Tops",
    subcategory: "Peasant Tops",
    gender: "Women",
    platform: "Trends",
    price: 1199,
    originalPrice: 2290,
    rating: 4.2,
    reviews: 690,
    colors: ["Pure White"],
    sizes: ["S", "M", "L"],
    available: true,
    description: "Bohemian inspired cotton top detailed with cutwork eyelet lace, mother-of-pearl buttons, and elasticated wrist cuffs.",
    priceHistory: [1690, 1490, 1290, 1199, 1199, 1199],
    folder: "tops",
    photoId: "1485968579580-b6d095142e6e"
  },
  {
    id: "CM-WTP-005",
    title: "Graphic Casual Cotton Boxy Tee",
    brand: "Ginger",
    category: "Tops",
    subcategory: "Tees",
    gender: "Women",
    platform: "Trends",
    price: 399,
    originalPrice: 799,
    rating: 4.1,
    reviews: 1820,
    colors: ["Lilac Graphic", "Butter Yellow"],
    sizes: ["S", "M", "L", "XL"],
    available: true,
    description: "Breathable cotton tee featuring minimal botanical line art, relaxed drop-shoulder cut, and soft bio-wash touch.",
    priceHistory: [599, 499, 449, 399, 399, 399],
    folder: "tops",
    photoId: "1508427953056-b00b8d78ebf5"
  },
  {
    id: "CM-WTP-006",
    title: "Satin Cowl-Neck Camisole Evening Top",
    brand: "Urbanic",
    category: "Tops",
    subcategory: "Camisoles",
    gender: "Women",
    platform: "Meesho",
    price: 449,
    originalPrice: 1199,
    rating: 4.0,
    reviews: 2150,
    colors: ["Rose Gold", "Midnight Navy"],
    sizes: ["S", "M", "L"],
    available: true,
    description: "Silky soft satin cami top featuring a flowing cowl neck and adjustable micro-straps. Elevates jeans or blazer sets.",
    priceHistory: [699, 599, 499, 449, 449, 449],
    folder: "tops",
    photoId: "1529139574466-a303027c1d8b"
  },
  {
    id: "CM-WTP-007",
    title: "Smocked Ruffled Off-Shoulder Bardot Top",
    brand: "Athena",
    category: "Tops",
    subcategory: "Bardot Tops",
    gender: "Women",
    platform: "Flipkart",
    price: 649,
    originalPrice: 1499,
    rating: 4.3,
    reviews: 890,
    colors: ["Coral Red", "Navy Dots"],
    sizes: ["S", "M", "L"],
    available: false,
    description: "Charming elasticated off-shoulder top with smocked waistline, flared ruffle trim, and soft floral print.",
    priceHistory: [999, 899, 749, 649, 649, 649],
    folder: "tops",
    photoId: "1516762689617-e1cffcef479d"
  },

  // ==========================================
  // 9. WOMEN'S JEANS (6 items)
  // ==========================================
  {
    id: "CM-WJN-001",
    title: "High-Rise Wide-Leg Flare Denim Jeans",
    brand: "Levi's",
    category: "Women's Jeans",
    subcategory: "Wide Leg Jeans",
    gender: "Women",
    platform: "Amazon",
    price: 1899,
    originalPrice: 3899,
    rating: 4.6,
    reviews: 2310,
    colors: ["Classic Medium Indigo", "Light Bleach Wash"],
    sizes: ["26", "28", "30", "32"],
    available: true,
    description: "Flattering high-waisted wide-leg jeans with 70s flair, crafted in vintage-feel non-stretch denim with fitted hip.",
    priceHistory: [2699, 2399, 2099, 1899, 1899, 1899],
    folder: "women-jeans",
    photoId: "1541099649105-f69ad21f3246"
  },
  {
    id: "CM-WJN-002",
    title: "Ankle-Length Vintage Mom Fit Jeans",
    brand: "H&M",
    category: "Women's Jeans",
    subcategory: "Mom Jeans",
    gender: "Women",
    platform: "Myntra",
    price: 1499,
    originalPrice: 2499,
    rating: 4.4,
    reviews: 1870,
    colors: ["Washed Denim Blue", "Charcoal Grey"],
    sizes: ["26", "28", "30", "32"],
    available: true,
    description: "Relaxed high-waist 5-pocket mom jeans in washed cotton denim with tapered legs and comfortable room through hips.",
    priceHistory: [1999, 1799, 1599, 1499, 1499, 1499],
    folder: "women-jeans",
    photoId: "1576995853123-5a10305d93c0"
  },
  {
    id: "CM-WJN-003",
    title: "Super Skinny Sculpt High-Waist Jeans",
    brand: "Only",
    category: "Women's Jeans",
    subcategory: "Skinny Jeans",
    gender: "Women",
    platform: "AJIO",
    price: 1299,
    originalPrice: 2799,
    rating: 4.3,
    reviews: 1420,
    colors: ["Dark Navy", "Solid Black"],
    sizes: ["26", "28", "30", "32", "34"],
    available: true,
    description: "Contouring high-waist power stretch jeans that sculpt the hips and calves while offering 360-degree all-day flexibility.",
    priceHistory: [1899, 1699, 1499, 1299, 1299, 1299],
    folder: "women-jeans",
    photoId: "1584370848010-d7fe6bc767ec"
  },
  {
    id: "CM-WJN-004",
    title: "Straight Fit Slit Hem Fashion Jeans",
    brand: "Zara",
    category: "Women's Jeans",
    subcategory: "Straight Jeans",
    gender: "Women",
    platform: "Trends",
    price: 1699,
    originalPrice: 3290,
    rating: 4.5,
    reviews: 640,
    colors: ["Mid-Wash Vintage"],
    sizes: ["26", "28", "30"],
    available: true,
    description: "Full-length straight leg jeans featuring clean side ankle slits tailored to showcase designer heels or chunky platform sneakers.",
    priceHistory: [2490, 2190, 1890, 1699, 1699, 1699],
    folder: "women-jeans",
    photoId: "1551803091-e20673f15770"
  },
  {
    id: "CM-WJN-005",
    title: "Distressed Knee Cut Boyfriend Jeans",
    brand: "Kraus Jeans",
    category: "Women's Jeans",
    subcategory: "Boyfriend Jeans",
    gender: "Women",
    platform: "Flipkart",
    price: 999,
    originalPrice: 2299,
    rating: 4.1,
    reviews: 1530,
    colors: ["Light Acid Wash"],
    sizes: ["28", "30", "32"],
    available: true,
    description: "Slouchy mid-rise boyfriend jeans with laid-back ripped knee details, rolled hem cuffs, and soft washed denim handfeel.",
    priceHistory: [1499, 1299, 1149, 999, 999, 999],
    folder: "women-jeans",
    photoId: "1598554747436-c9293d6a588f"
  },
  {
    id: "CM-WJN-006",
    title: "Paperbag Waist Belted Denim Trousers",
    brand: "Tokyo Talkies",
    category: "Women's Jeans",
    subcategory: "Paperbag Jeans",
    gender: "Women",
    platform: "Meesho",
    price: 699,
    originalPrice: 1599,
    rating: 4.2,
    reviews: 980,
    colors: ["Indigo Blue", "Ice Wash"],
    sizes: ["26", "28", "30", "32"],
    available: false,
    description: "Trendy paperbag denim trousers with gathered ruffle waist, removable denim tie belt, and tapered cropped ankles.",
    priceHistory: [999, 899, 799, 699, 699, 699],
    folder: "women-jeans",
    photoId: "1517841905240-472988babdf9"
  },

  // ==========================================
  // 10. WOMEN'S KURTIS (8 items)
  // ==========================================
  {
    id: "CM-WKT-001",
    title: "Indigo Block Print Straight Cotton Kurti",
    brand: "Anouk",
    category: "Kurtis",
    subcategory: "Straight Kurtis",
    gender: "Women",
    platform: "Flipkart",
    price: 749,
    originalPrice: 1499,
    rating: 4.5,
    reviews: 2080,
    colors: ["Indigo Blue", "Rust Orange"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    available: true,
    description: "Breathable pure cotton daily kurti with artisanal hand-block inspired all-over motifs, side slits, and round neck with notch.",
    priceHistory: [899, 849, 799, 749, 749, 749],
    folder: "kurtis",
    photoId: "1617627143750-d86bc21e42bb"
  },
  {
    id: "CM-WKT-002",
    title: "Flared Anarkali Chanderi Silk Kurti",
    brand: "Biba",
    category: "Kurtis",
    subcategory: "Anarkali Kurtis",
    gender: "Women",
    platform: "Myntra",
    price: 1799,
    originalPrice: 3599,
    rating: 4.6,
    reviews: 1320,
    colors: ["Teal Green", "Deep Maroon"],
    sizes: ["S", "M", "L", "XL"],
    available: true,
    description: "Regal floor-length Anarkali kurti crafted in gossamer Chanderi silk blend with gold zari border and woven floral yoke.",
    priceHistory: [2599, 2299, 1999, 1799, 1799, 1799],
    folder: "kurtis",
    photoId: "1617627143750-d86bc21e42bb"
  },
  {
    id: "CM-WKT-003",
    title: "Embroidered Chikankari Handcrafted Kurti",
    brand: "Ada Lucknow",
    category: "Kurtis",
    subcategory: "Chikankari Kurtis",
    gender: "Women",
    platform: "Amazon",
    price: 1299,
    originalPrice: 2499,
    rating: 4.7,
    reviews: 940,
    colors: ["Pristine White", "Pastel Peach", "Sky Blue"],
    sizes: ["38", "40", "42", "44"],
    available: true,
    description: "Authentic Lucknowi hand-embroidered modal cotton kurti showcasing intricate Bakhiya and Phanda stitches with inner slip included.",
    priceHistory: [1899, 1699, 1499, 1299, 1299, 1299],
    folder: "kurtis",
    photoId: "1610030469983-98e550d6193c"
  },
  {
    id: "CM-WKT-004",
    title: "A-Line Floral Print Tunic Kurti",
    brand: "W for Woman",
    category: "Kurtis",
    subcategory: "A-Line Kurtis",
    gender: "Women",
    platform: "AJIO",
    price: 999,
    originalPrice: 1999,
    rating: 4.3,
    reviews: 1110,
    colors: ["Mustard Floral", "Ivory Olive"],
    sizes: ["S", "M", "L", "XL"],
    available: true,
    description: "Modern fusion A-line tunic kurti with mandarin collar, rolled-up sleeve tabs, and contemporary asymmetrical hemline.",
    priceHistory: [1499, 1299, 1149, 999, 999, 999],
    folder: "kurtis",
    photoId: "1609357605129-26f69add5d6e"
  },
  {
    id: "CM-WKT-005",
    title: "Bandhani Print Rayon Flared Kurti",
    brand: "Jaipur Kurti",
    category: "Kurtis",
    subcategory: "Flared Kurtis",
    gender: "Women",
    platform: "Meesho",
    price: 499,
    originalPrice: 1299,
    rating: 4.2,
    reviews: 3450,
    colors: ["Ruby Red", "Royal Blue"],
    sizes: ["M", "L", "XL", "XXL"],
    available: true,
    description: "Vibrant Rajasthani tie-dye Bandhani print rayon kurti featuring gota patti lace border and 3/4th regular sleeves.",
    priceHistory: [799, 699, 599, 499, 499, 499],
    folder: "kurtis",
    photoId: "1572804013309-59a88b7e92f1"
  },
  {
    id: "CM-WKT-006",
    title: "Khadi Cotton Casual Everyday Kurti",
    brand: "FabIndia",
    category: "Kurtis",
    subcategory: "Casual Kurtis",
    gender: "Women",
    platform: "Trends",
    price: 1199,
    originalPrice: 1890,
    rating: 4.4,
    reviews: 620,
    colors: ["Earthy Terracotta", "Off White"],
    sizes: ["S", "M", "L", "XL"],
    available: true,
    description: "Hand-spun breathable khadi cotton kurti tailored with coconut shell buttons, side pockets, and relaxed straight silhouette.",
    priceHistory: [1590, 1450, 1290, 1199, 1199, 1199],
    folder: "kurtis",
    photoId: "1596755094514-f87e34085b2c"
  },
  {
    id: "CM-WKT-007",
    title: "Mirror Work Festive Rayon Kurti",
    brand: "Aurelia",
    category: "Kurtis",
    subcategory: "Festive Kurtis",
    gender: "Women",
    platform: "Myntra",
    price: 899,
    originalPrice: 1799,
    rating: 4.3,
    reviews: 1540,
    colors: ["Magenta Pink", "Emerald"],
    sizes: ["S", "M", "L", "XL"],
    available: true,
    description: "Festive jewel-toned straight kurti highlighted with genuine mirror work on the neck placket and gold foil prints.",
    priceHistory: [1399, 1199, 999, 899, 899, 899],
    folder: "kurtis",
    photoId: "1583391733956-3750e0ff4e8b"
  },
  {
    id: "CM-WKT-008",
    title: "Layered Angrakha Style Ethnic Kurti",
    brand: "Libas",
    category: "Kurtis",
    subcategory: "Angrakha Kurtis",
    gender: "Women",
    platform: "Flipkart",
    price: 949,
    originalPrice: 2199,
    rating: 4.4,
    reviews: 1890,
    colors: ["Navy Gold"],
    sizes: ["S", "M", "L", "XL"],
    available: false,
    description: "Traditional overlap Angrakha style kurti with side dori tie-up tassels, tiered hem, and contrast piping accents.",
    priceHistory: [1499, 1299, 1099, 949, 949, 949],
    folder: "kurtis",
    photoId: "1617627143750-d86bc21e42bb"
  },

  // ==========================================
  // 11. WOMEN'S ETHNIC WEAR (6 items)
  // ==========================================
  {
    id: "CM-WET-001",
    title: "Banarasi Silk Jacquard Woven Saree",
    brand: "Kalamandir",
    category: "Ethnic Wear",
    subcategory: "Sarees",
    gender: "Women",
    platform: "Myntra",
    price: 2499,
    originalPrice: 5999,
    rating: 4.6,
    reviews: 1840,
    colors: ["Royal Crimson Red", "Peacock Blue"],
    sizes: ["Free Size (5.5m + Blouse)"],
    available: true,
    description: "Traditional Banarasi art silk saree woven with intricate floral zari jaal all over the body, heavy pallu, and matching unstitched blouse piece.",
    priceHistory: [3899, 3299, 2899, 2499, 2499, 2499],
    folder: "ethnic-wear",
    photoId: "1610030469983-98e550d6193c"
  },
  {
    id: "CM-WET-002",
    title: "Sequined Semi-Stitched Net Lehenga Choli",
    brand: "Chhabra 555",
    category: "Ethnic Wear",
    subcategory: "Lehengas",
    gender: "Women",
    platform: "Amazon",
    price: 3499,
    originalPrice: 8999,
    rating: 4.5,
    reviews: 790,
    colors: ["Blush Rose Gold", "Navy Blue"],
    sizes: ["Semi-Stitched (Up to 42)"],
    available: true,
    description: "Bridal and festive semi-stitched lehenga with tiered can-can flare, shimmer sequin work, embroidered blouse piece, and scalloped net dupatta.",
    priceHistory: [5499, 4699, 3999, 3499, 3499, 3499],
    folder: "ethnic-wear",
    photoId: "1583391733956-3750e0ff4e8b"
  },
  {
    id: "CM-WET-003",
    title: "Embroidered Kurta with Palazzo & Dupatta Set",
    brand: "Biba",
    category: "Ethnic Wear",
    subcategory: "Suit Sets",
    gender: "Women",
    platform: "AJIO",
    price: 2199,
    originalPrice: 4299,
    rating: 4.4,
    reviews: 1120,
    colors: ["Powder Blue", "Peach"],
    sizes: ["S", "M", "L", "XL"],
    available: true,
    description: "Complete 3-piece festive ethnic suit set featuring pure chanderi embroidered straight kurta, matching flared palazzo pants, and printed organza dupatta.",
    priceHistory: [3199, 2799, 2499, 2199, 2199, 2199],
    folder: "ethnic-wear",
    photoId: "1617627143750-d86bc21e42bb"
  },
  {
    id: "CM-WET-004",
    title: "Pure Handloom Kanjeevaram Silk Saree",
    brand: "Pothys",
    category: "Ethnic Wear",
    subcategory: "Sarees",
    gender: "Women",
    platform: "Trends",
    price: 3999,
    originalPrice: 7999,
    rating: 4.7,
    reviews: 620,
    colors: ["Temple Gold & Maroon"],
    sizes: ["Free Size"],
    available: true,
    description: "Heirloom grade woven silk saree featuring traditional temple borders, contrast korvai pallu, and rich antique golden threads.",
    priceHistory: [5999, 4999, 4499, 3999, 3999, 3999],
    folder: "ethnic-wear",
    photoId: "1583391733981-8498409f4c65"
  },
  {
    id: "CM-WET-005",
    title: "Printed Cotton Sharara Suit Set",
    brand: "Aasiya",
    category: "Ethnic Wear",
    subcategory: "Sharara Sets",
    gender: "Women",
    platform: "Flipkart",
    price: 1199,
    originalPrice: 2799,
    rating: 4.2,
    reviews: 2310,
    colors: ["Mint Green", "Sunny Yellow"],
    sizes: ["S", "M", "L", "XL"],
    available: true,
    description: "Playful floral printed cotton peplum short kurta paired with voluminous multi-tiered ruffled sharara pants and matching voile dupatta.",
    priceHistory: [1699, 1499, 1349, 1199, 1199, 1199],
    folder: "ethnic-wear",
    photoId: "1609357605129-26f69add5d6e"
  },
  {
    id: "CM-WET-006",
    title: "Floral Printed Ready-to-Wear Georgette Saree",
    brand: "Saree Swarg",
    category: "Ethnic Wear",
    subcategory: "Sarees",
    gender: "Women",
    platform: "Meesho",
    price: 699,
    originalPrice: 1999,
    rating: 4.1,
    reviews: 3100,
    colors: ["Lavender Floral", "Black Rose"],
    sizes: ["Free Size (Pre-Pleated)"],
    available: false,
    description: "Hassle-free 1-minute pre-stitched pleated georgette saree with adjustable waist hooks and stitched sleeveless blouse.",
    priceHistory: [1099, 899, 799, 699, 699, 699],
    folder: "ethnic-wear",
    photoId: "1572804013309-59a88b7e92f1"
  },

  // ==========================================
  // 12. WOMEN'S JACKETS (6 items)
  // ==========================================
  {
    id: "CM-WJK-001",
    title: "Double-Breasted Classic Belted Trench Coat",
    brand: "Mango",
    category: "Women's Jackets",
    subcategory: "Trench Coats",
    gender: "Women",
    platform: "Myntra",
    price: 3299,
    originalPrice: 6990,
    rating: 4.7,
    reviews: 580,
    colors: ["Camel Beige", "Classic Black"],
    sizes: ["XS", "S", "M", "L"],
    available: true,
    description: "Water-repellent tailored trench coat crafted with storm flaps, tortoiseshell buttons, buckle waist belt, and deep welt pockets.",
    priceHistory: [4990, 4290, 3790, 3299, 3299, 3299],
    folder: "women-jackets",
    photoId: "1539533018447-63fcce2678e3"
  },
  {
    id: "CM-WJK-002",
    title: "Cropped Moto Faux Leather Biker Jacket",
    brand: "Zara",
    category: "Women's Jackets",
    subcategory: "Leather Jackets",
    gender: "Women",
    platform: "AJIO",
    price: 2499,
    originalPrice: 4590,
    rating: 4.5,
    reviews: 940,
    colors: ["Black", "Oxblood Burgundy"],
    sizes: ["S", "M", "L"],
    available: true,
    description: "Sleek cropped vegan leather biker jacket with asymmetrical silver front zipper, lapel snap studs, and belted waist trim.",
    priceHistory: [3590, 3190, 2790, 2499, 2499, 2499],
    folder: "women-jackets",
    photoId: "1551028719-00167b16eac5"
  },
  {
    id: "CM-WJK-003",
    title: "Oversized Drop-Shoulder Denim Jacket",
    brand: "Levi's",
    category: "Women's Jackets",
    subcategory: "Denim Jackets",
    gender: "Women",
    platform: "Amazon",
    price: 2199,
    originalPrice: 4299,
    rating: 4.4,
    reviews: 1420,
    colors: ["Vintage Light Blue", "Washed Charcoal"],
    sizes: ["XS", "S", "M", "L"],
    available: true,
    description: "Boyfriend-fit rugged cotton trucker jacket designed with drop shoulders, chest button-flap pockets, and adjustable waist tabs.",
    priceHistory: [2999, 2699, 2399, 2199, 2199, 2199],
    folder: "women-jackets",
    photoId: "1544923246-77307dd654cb"
  },
  {
    id: "CM-WJK-004",
    title: "Short Padded Puffer Winter Jacket with Hood",
    brand: "H&M",
    category: "Women's Jackets",
    subcategory: "Puffer Jackets",
    gender: "Women",
    platform: "Trends",
    price: 1799,
    originalPrice: 3499,
    rating: 4.3,
    reviews: 810,
    colors: ["Sage Green", "Matte Black"],
    sizes: ["S", "M", "L"],
    available: true,
    description: "Thermal insulated quilted puffer jacket featuring high stand collar, removable hood, fleece-lined pockets, and wind-seal elastic cuffs.",
    priceHistory: [2599, 2299, 1999, 1799, 1799, 1799],
    folder: "women-jackets",
    photoId: "1515886657613-9f3515b0c78f"
  },
  {
    id: "CM-WJK-005",
    title: "Tailored Open-Front Formal Work Blazer",
    brand: "Van Heusen",
    category: "Women's Jackets",
    subcategory: "Blazers",
    gender: "Women",
    platform: "Flipkart",
    price: 1699,
    originalPrice: 3499,
    rating: 4.4,
    reviews: 670,
    colors: ["Powder Pink", "Navy Blue"],
    sizes: ["S", "M", "L", "XL"],
    available: true,
    description: "Structured workwear blazer with peaked lapels, shoulder padding for crisp silhouette, and full satin interior lining.",
    priceHistory: [2499, 2199, 1899, 1699, 1699, 1699],
    folder: "women-jackets",
    photoId: "1507679799987-c73779587ccf"
  },
  {
    id: "CM-WJK-006",
    title: "Faux Shearling Teddy Fleece Zip Jacket",
    brand: "Forever 21",
    category: "Women's Jackets",
    subcategory: "Fleece Jackets",
    gender: "Women",
    platform: "Meesho",
    price: 999,
    originalPrice: 2299,
    rating: 4.2,
    reviews: 1530,
    colors: ["Teddy Beige", "Dusty Rose"],
    sizes: ["S", "M", "L"],
    available: false,
    description: "Ultra-plush cozy sherpa fleece zip-up jacket with contrast nylon chest pocket and funnel collar.",
    priceHistory: [1499, 1299, 1149, 999, 999, 999],
    folder: "women-jackets",
    photoId: "1548883354-7622d03aca27"
  },

  // ==========================================
  // 13. KIDS WEAR (7 items)
  // ==========================================
  {
    id: "CM-KID-001",
    title: "Boys Pure Cotton Graphic T-Shirt & Shorts Set",
    brand: "Mothercare",
    category: "Kids Wear",
    subcategory: "Boys Sets",
    gender: "Kids",
    platform: "Myntra",
    price: 699,
    originalPrice: 1499,
    rating: 4.5,
    reviews: 1240,
    colors: ["Dino Yellow & Navy", "Safari Green"],
    sizes: ["2-3Y", "3-4Y", "5-6Y", "7-8Y"],
    available: true,
    description: "100% hypoallergenic soft cotton 2-piece outfit featuring dinosaur graphic print tee and elasticated drawstring shorts.",
    priceHistory: [999, 899, 799, 699, 699, 699],
    folder: "kids-wear",
    photoId: "1519238263530-99bdd11df2ea"
  },
  {
    id: "CM-KID-002",
    title: "Girls Floral Tiered Cotton Summer Frock",
    brand: "Gini & Jony",
    category: "Kids Wear",
    subcategory: "Girls Dresses",
    gender: "Kids",
    platform: "Amazon",
    price: 799,
    originalPrice: 1699,
    rating: 4.6,
    reviews: 980,
    colors: ["Pastel Floral Pink", "Sky Floral"],
    sizes: ["3-4Y", "5-6Y", "7-8Y", "9-10Y"],
    available: true,
    description: "Charming breathable cotton frock with gathered tier ruffles, back button closure, and matching hairband included.",
    priceHistory: [1199, 1049, 899, 799, 799, 799],
    folder: "kids-wear",
    photoId: "1518831959646-742c3a14ebf7"
  },
  {
    id: "CM-KID-003",
    title: "Unisex Denim Dungarees with Striped Inner Tee",
    brand: "H&M",
    category: "Kids Wear",
    subcategory: "Dungarees",
    gender: "Kids",
    platform: "AJIO",
    price: 1199,
    originalPrice: 2299,
    rating: 4.4,
    reviews: 650,
    colors: ["Medium Denim Blue"],
    sizes: ["1-2Y", "2-3Y", "3-4Y"],
    available: true,
    description: "Adjustable clasp denim dungarees with front bib pocket, soft washed denim, and long-sleeve striped jersey tee.",
    priceHistory: [1699, 1499, 1349, 1199, 1199, 1199],
    folder: "kids-wear",
    photoId: "1503454537195-1dcabb73ffb9"
  },
  {
    id: "CM-KID-004",
    title: "Boys Hooded Lightweight Padded Winter Vest",
    brand: "U.S. Polo Assn. Kids",
    category: "Kids Wear",
    subcategory: "Kids Jackets",
    gender: "Kids",
    platform: "Trends",
    price: 899,
    originalPrice: 1899,
    rating: 4.3,
    reviews: 430,
    colors: ["Navy / Red Colorblock"],
    sizes: ["4-5Y", "6-7Y", "8-9Y"],
    available: true,
    description: "Sleeveless insulated puffer gilet jacket with warm hood, zip pockets, and water-resistant shell for outdoor play.",
    priceHistory: [1399, 1199, 999, 899, 899, 899],
    folder: "kids-wear",
    photoId: "1471286174890-9c112ffca56a"
  },
  {
    id: "CM-KID-005",
    title: "Girls Sparkle Tulle Birthday Party Dress",
    brand: "Hopscotch",
    category: "Kids Wear",
    subcategory: "Girls Party Wear",
    gender: "Kids",
    platform: "Flipkart",
    price: 1049,
    originalPrice: 2499,
    rating: 4.5,
    reviews: 1420,
    colors: ["Frozen Blue Tulle", "Princess Pink"],
    sizes: ["2-3Y", "4-5Y", "6-7Y"],
    available: true,
    description: "Magical multi-layer shimmer tulle party dress with sequin-embroidered bodice and comfortable 100% cotton inner lining.",
    priceHistory: [1599, 1399, 1199, 1049, 1049, 1049],
    folder: "kids-wear",
    photoId: "1622290291468-a28f7a7dc6a8"
  },
  {
    id: "CM-KID-006",
    title: "Toddlers Organic Cotton Printed Sleepsuit 2-Pack",
    brand: "FirstCry",
    category: "Kids Wear",
    subcategory: "Baby Wear",
    gender: "Kids",
    platform: "Meesho",
    price: 499,
    originalPrice: 1199,
    rating: 4.2,
    reviews: 2150,
    colors: ["Animals & Clouds"],
    sizes: ["0-3M", "3-6M", "6-12M"],
    available: true,
    description: "Pack of 2 ultra-soft GOTS certified organic cotton footed onesies with two-way easy diaper change zippers.",
    priceHistory: [799, 699, 599, 499, 499, 499],
    folder: "kids-wear",
    photoId: "1515488042361-ee00e0ddd4e4"
  },
  {
    id: "CM-KID-007",
    title: "Boys Cotton Chino Pants with Suspenders",
    brand: "Marks & Spencer Kids",
    category: "Kids Wear",
    subcategory: "Boys Formal",
    gender: "Kids",
    platform: "AJIO",
    price: 949,
    originalPrice: 1999,
    rating: 4.4,
    reviews: 380,
    colors: ["Classic Beige"],
    sizes: ["3-4Y", "5-6Y", "7-8Y"],
    available: false,
    description: "Smart twill chino trousers with adjustable inner waist button tabs and removable striped elastic suspenders.",
    priceHistory: [1499, 1299, 1099, 949, 949, 949],
    folder: "kids-wear",
    photoId: "1508214751196-bcfd4ca60f91"
  },

  // ==========================================
  // 14. SNEAKERS (8 items)
  // ==========================================
  {
    id: "CM-SNK-001",
    title: "Air Max Retro Low Lifestyle Sneakers",
    brand: "Nike",
    category: "Sneakers",
    subcategory: "Lifestyle Sneakers",
    gender: "Unisex",
    platform: "Nike",
    price: 4495,
    originalPrice: 6495,
    rating: 4.8,
    reviews: 2890,
    colors: ["Triple White", "Black / University Red"],
    sizes: ["UK 7", "UK 8", "UK 9", "UK 10", "UK 11"],
    available: true,
    description: "Iconic streetwear silhouette with visible Max Air heel cushioning, durable stitched leather overlays, and rubber waffle outsole.",
    priceHistory: [5795, 5295, 4995, 4495, 4495, 4495],
    folder: "sneakers",
    photoId: "1542291026-7eec264c27ff"
  },
  {
    id: "CM-SNK-002",
    title: "Classic Canvas Everyday Low-Top Sneakers",
    brand: "Puma",
    category: "Sneakers",
    subcategory: "Canvas Sneakers",
    gender: "Unisex",
    platform: "Meesho",
    price: 1399,
    originalPrice: 2999,
    rating: 4.1,
    reviews: 404,
    colors: ["Bright Crimson Red", "Cloud White"],
    sizes: ["6", "7", "8", "9", "10"],
    available: true,
    description: "Lightweight canvas vulcanized sneakers engineered with a cushioned SoftFoam+ comfort sockliner for all-day city walking.",
    priceHistory: [1799, 1699, 1599, 1399, 1399, 1399],
    folder: "sneakers",
    photoId: "1607522370275-f14206abe5d3"
  },
  {
    id: "CM-SNK-003",
    title: "Grand Court Cloudfoam Leather Tennis Sneakers",
    brand: "Adidas",
    category: "Sneakers",
    subcategory: "Court Sneakers",
    gender: "Men",
    platform: "Myntra",
    price: 2699,
    originalPrice: 5599,
    rating: 4.5,
    reviews: 3410,
    colors: ["Cloud White / Core Black", "White / Green"],
    sizes: ["UK 7", "UK 8", "UK 9", "UK 10"],
    available: true,
    description: "Vintage 70s court-inspired synthetic leather shoes with contrast 3-Stripes and plush Cloudfoam midsole cushioning.",
    priceHistory: [3999, 3499, 2999, 2699, 2699, 2699],
    folder: "sneakers",
    photoId: "1584735935682-2f2b69dff9d2"
  },
  {
    id: "CM-SNK-004",
    title: "574 Core Heritage Suede Running Sneakers",
    brand: "New Balance",
    category: "Sneakers",
    subcategory: "Retro Runners",
    gender: "Unisex",
    platform: "Amazon",
    price: 3999,
    originalPrice: 7999,
    rating: 4.7,
    reviews: 1890,
    colors: ["Heritage Grey", "Navy Blue"],
    sizes: ["UK 7", "UK 8", "UK 9", "UK 10", "UK 11"],
    available: true,
    description: "Timeless hybrid road/trail sneaker with ENCAP midsole support, premium pigskin suede upper, and breathable mesh inserts.",
    priceHistory: [5999, 5299, 4499, 3999, 3999, 3999],
    folder: "sneakers",
    photoId: "1539185441755-769473a23570"
  },
  {
    id: "CM-SNK-005",
    title: "Chuck 70 High-Top Vintage Canvas Sneakers",
    brand: "Converse",
    category: "Sneakers",
    subcategory: "High-Top Sneakers",
    gender: "Unisex",
    platform: "AJIO",
    price: 2999,
    originalPrice: 4999,
    rating: 4.6,
    reviews: 2150,
    colors: ["Classic Black", "Parchment White"],
    sizes: ["UK 6", "UK 7", "UK 8", "UK 9", "UK 10"],
    available: true,
    description: "Upgraded premium high-top sneakers with 12oz organic canvas, winged tongue stitching, OrthoLite insole, and vintage ankle patch.",
    priceHistory: [3999, 3599, 3299, 2999, 2999, 2999],
    folder: "sneakers",
    photoId: "1608231387042-66d1773070a5"
  },
  {
    id: "CM-SNK-006",
    title: "Old Skool Suede Stripe Skate Sneakers",
    brand: "Vans",
    category: "Sneakers",
    subcategory: "Skate Shoes",
    gender: "Unisex",
    platform: "Flipkart",
    price: 2399,
    originalPrice: 4499,
    rating: 4.5,
    reviews: 1720,
    colors: ["Black & White Sidestripe", "Checkerboard"],
    sizes: ["UK 6", "UK 7", "UK 8", "UK 9", "UK 10"],
    available: true,
    description: "Heritage low-top skate shoe with durable canvas and suede uppers, re-enforced toe caps, padded collars, and signature waffle rubber sole.",
    priceHistory: [3299, 2899, 2599, 2399, 2399, 2399],
    folder: "sneakers",
    photoId: "1525966222134-fcfa99b8ae77"
  },
  {
    id: "CM-SNK-007",
    title: "Slip-On Chunky Knit Walking Sneakers",
    brand: "Red Tape",
    category: "Sneakers",
    subcategory: "Walking Shoes",
    gender: "Men",
    platform: "Trends",
    price: 1199,
    originalPrice: 3899,
    rating: 4.2,
    reviews: 3100,
    colors: ["All Black", "Grey Heather"],
    sizes: ["6", "7", "8", "9", "10"],
    available: true,
    description: "Sock-like slip-on athletic sneakers with breathable mesh knit upper, memory foam footbed, and shock-absorbing chunky EVA sole.",
    priceHistory: [1699, 1499, 1299, 1199, 1199, 1199],
    folder: "sneakers",
    photoId: "1595950653106-6c9ebd614d3a"
  },
  {
    id: "CM-SNK-008",
    title: "Rebound Joy High-Top Basketball Sneakers",
    brand: "Puma",
    category: "Sneakers",
    subcategory: "High-Top Sneakers",
    gender: "Men",
    platform: "AJIO",
    price: 2799,
    originalPrice: 5499,
    rating: 4.4,
    reviews: 890,
    colors: ["White / Black / Red"],
    sizes: ["UK 7", "UK 8", "UK 9", "UK 10"],
    available: false,
    description: "Retro basketball silhouette featuring padded high collar for ankle support, perforated vamp, and durable rubber traction cupsole.",
    priceHistory: [3899, 3499, 3099, 2799, 2799, 2799],
    folder: "sneakers",
    photoId: "1552346154-21d32810aba3"
  },

  // ==========================================
  // 15. CASUAL & FORMAL SHOES (6 items)
  // ==========================================
  {
    id: "CM-CSH-001",
    title: "Genuine Leather Handcrafted Oxford Brogues",
    brand: "Bata",
    category: "Shoes",
    subcategory: "Formal Shoes",
    gender: "Men",
    platform: "Amazon",
    price: 1899,
    originalPrice: 3499,
    rating: 4.4,
    reviews: 1450,
    colors: ["Tan Brown", "Classic Black"],
    sizes: ["UK 7", "UK 8", "UK 9", "UK 10", "UK 11"],
    available: true,
    description: "Polished genuine crust leather oxford shoes with decorative wingtip brogue perforations, stacked heel, and leather-lined insole.",
    priceHistory: [2599, 2299, 2099, 1899, 1899, 1899],
    folder: "shoes",
    photoId: "1533867617858-e7b97e060509"
  },
  {
    id: "CM-CSH-002",
    title: "Suede Penny Loafers with Moccasin Stitching",
    brand: "Hush Puppies",
    category: "Shoes",
    subcategory: "Loafers",
    gender: "Men",
    platform: "Myntra",
    price: 2499,
    originalPrice: 4999,
    rating: 4.6,
    reviews: 820,
    colors: ["Navy Suede", "Camel Brown"],
    sizes: ["UK 7", "UK 8", "UK 9", "UK 10"],
    available: true,
    description: "Velvety genuine suede slip-on penny loafers detailed with hand-sewn apron moccasin toe and flexible driving shoe rubber nubs.",
    priceHistory: [3499, 3099, 2799, 2499, 2499, 2499],
    folder: "shoes",
    photoId: "1582897103233-6447781b0a70"
  },
  {
    id: "CM-CSH-003",
    title: "Classic Chelsea Leather Ankle Boots",
    brand: "Red Chief",
    category: "Shoes",
    subcategory: "Boots",
    gender: "Men",
    platform: "Flipkart",
    price: 2299,
    originalPrice: 4899,
    rating: 4.3,
    reviews: 1670,
    colors: ["Rust Tan", "Jet Black"],
    sizes: ["UK 7", "UK 8", "UK 9", "UK 10"],
    available: true,
    description: "Rugged pull-on Chelsea boots featuring elasticated side gores, back pull loop, genuine leather upper, and anti-slip lug tread.",
    priceHistory: [3199, 2899, 2599, 2299, 2299, 2299],
    folder: "shoes",
    photoId: "1608256246200-53e635b5b65f"
  },
  {
    id: "CM-CSH-004",
    title: "Breathable Canvas Espadrilles Slip-Ons",
    brand: "Soludos",
    category: "Shoes",
    subcategory: "Casual Shoes",
    gender: "Unisex",
    platform: "AJIO",
    price: 999,
    originalPrice: 1999,
    rating: 4.2,
    reviews: 540,
    colors: ["Sand White", "Navy Stripe"],
    sizes: ["UK 6", "UK 7", "UK 8", "UK 9"],
    available: true,
    description: "Mediterranean-inspired summer espadrilles with natural jute braided rope midsole, cotton canvas upper, and rubber sole.",
    priceHistory: [1499, 1299, 1149, 999, 999, 999],
    folder: "shoes",
    photoId: "1560343090-f0409e92791a"
  },
  {
    id: "CM-CSH-005",
    title: "Formal Slip-On Derby Shoes with Elastic Gusset",
    brand: "Woodland",
    category: "Shoes",
    subcategory: "Formal Shoes",
    gender: "Men",
    platform: "Trends",
    price: 1799,
    originalPrice: 3295,
    rating: 4.4,
    reviews: 930,
    colors: ["Deep Brown", "Black"],
    sizes: ["UK 7", "UK 8", "UK 9", "UK 10"],
    available: true,
    description: "Supple polished leather office shoes with hidden elasticated tongue gussets for quick entry and durable rubber soles.",
    priceHistory: [2495, 2195, 1995, 1799, 1799, 1799],
    folder: "shoes",
    photoId: "1614252369475-531eba835eb1"
  },
  {
    id: "CM-CSH-006",
    title: "Casual Driving Shoes with Metal Bit Buckle",
    brand: "Carlton London",
    category: "Shoes",
    subcategory: "Loafers",
    gender: "Men",
    platform: "Meesho",
    price: 849,
    originalPrice: 1999,
    rating: 4.0,
    reviews: 1840,
    colors: ["Tan Brown"],
    sizes: ["UK 7", "UK 8", "UK 9", "UK 10"],
    available: false,
    description: "Smart textured synthetic leather moccasins embellished with horsebit metal hardware across the vamp.",
    priceHistory: [1199, 1049, 949, 849, 849, 849],
    folder: "shoes",
    photoId: "1595341888016-a392ef81b7de"
  },

  // ==========================================
  // 16. SPORTSWEAR (7 items)
  // ==========================================
  {
    id: "CM-SPT-001",
    title: "Dri-FIT Moisture-Wicking Training Shorts",
    brand: "Nike",
    category: "Sportswear",
    subcategory: "Gym Shorts",
    gender: "Men",
    platform: "Nike",
    price: 1495,
    originalPrice: 2195,
    rating: 4.7,
    reviews: 1650,
    colors: ["Black / White Swoosh", "Iron Grey"],
    sizes: ["S", "M", "L", "XL"],
    available: true,
    description: "Lightweight 7-inch running and gym shorts featuring breathable mesh side panels, elastic drawcord waist, and deep media pocket.",
    priceHistory: [1995, 1895, 1695, 1495, 1495, 1495],
    folder: "sportswear",
    photoId: "1517838277536-f5f99be501cd"
  },
  {
    id: "CM-SPT-002",
    title: "Tiro 23 Tapered Soccer Track Pants",
    brand: "Adidas",
    category: "Sportswear",
    subcategory: "Track Pants",
    gender: "Men",
    platform: "Myntra",
    price: 1899,
    originalPrice: 3599,
    rating: 4.6,
    reviews: 2980,
    colors: ["Black / White Stripes", "Navy / White"],
    sizes: ["S", "M", "L", "XL"],
    available: true,
    description: "Football-inspired AEROREADY track pants with iconic 3-Stripes along the sides, ankle zips for quick shoe clearance, and secure zip pockets.",
    priceHistory: [2699, 2399, 2099, 1899, 1899, 1899],
    folder: "sportswear",
    photoId: "1518611012118-696072aa579a"
  },
  {
    id: "CM-SPT-003",
    title: "Seamless High-Waist Workout Leggings",
    brand: "Puma",
    category: "Sportswear",
    subcategory: "Tights",
    gender: "Women",
    platform: "Amazon",
    price: 1299,
    originalPrice: 2799,
    rating: 4.5,
    reviews: 1420,
    colors: ["Plum Purple", "Charcoal Black"],
    sizes: ["XS", "S", "M", "L"],
    available: true,
    description: "Squat-proof compression yoga tights engineered with compressive ribbed high waistband that never rolls down during high-intensity intervals.",
    priceHistory: [1999, 1699, 1499, 1299, 1299, 1299],
    folder: "sportswear",
    photoId: "1506126613408-eca07ce68773"
  },
  {
    id: "CM-SPT-004",
    title: "High-Support Zip-Front Sports Bra",
    brand: "Decathlon",
    category: "Sportswear",
    subcategory: "Sports Bras",
    gender: "Women",
    platform: "AJIO",
    price: 899,
    originalPrice: 1799,
    rating: 4.4,
    reviews: 1890,
    colors: ["Coral Pink", "Slate Black"],
    sizes: ["32B", "34B", "34C", "36C", "38D"],
    available: true,
    description: "Maximum bounce-reduction sports bra for running and cardio with easy front zipper, padded wide straps, and breathable racerback mesh.",
    priceHistory: [1299, 1149, 999, 899, 899, 899],
    folder: "sportswear",
    photoId: "1518310383802-640c2de311b2"
  },
  {
    id: "CM-SPT-005",
    title: "Active Quarter-Zip Thermal Running Pullover",
    brand: "Under Armour",
    category: "Sportswear",
    subcategory: "Gym Tops",
    gender: "Men",
    platform: "Flipkart",
    price: 1599,
    originalPrice: 2999,
    rating: 4.5,
    reviews: 780,
    colors: ["Carbon Heather", "Academy Blue"],
    sizes: ["M", "L", "XL"],
    available: true,
    description: "ColdGear microfleece quarter-zip top designed with 4-way stretch fabric, thumbholes on cuffs, and reflective chest logo for night safety.",
    priceHistory: [2199, 1899, 1749, 1599, 1599, 1599],
    folder: "sportswear",
    photoId: "1483721074576-579a571a09db"
  },
  {
    id: "CM-SPT-006",
    title: "Relaxed Fit Cotton French Terry Joggers",
    brand: "Performax",
    category: "Sportswear",
    subcategory: "Joggers",
    gender: "Men",
    platform: "Trends",
    price: 799,
    originalPrice: 1499,
    rating: 4.2,
    reviews: 1610,
    colors: ["Melange Grey", "Black"],
    sizes: ["S", "M", "L", "XL"],
    available: true,
    description: "Soft unbrushed French terry athletic joggers with comfortable ribbed waistband, deep zippered pockets, and tapered cuffs.",
    priceHistory: [1099, 999, 899, 799, 799, 799],
    folder: "sportswear",
    photoId: "1552374196-1ab2a1c593e8"
  },
  {
    id: "CM-SPT-007",
    title: "Quick-Dry Anti-Odor Gym Stringer Vest",
    brand: "HRX by Hrithik Roshan",
    category: "Sportswear",
    subcategory: "Vests",
    gender: "Men",
    platform: "Meesho",
    price: 349,
    originalPrice: 899,
    rating: 4.1,
    reviews: 2450,
    colors: ["Neon Lime", "Charcoal Black"],
    sizes: ["M", "L", "XL"],
    available: false,
    description: "Deep-cut bodybuilding gym tank top with antibacterial silver ion finish and flatlock seams to prevent chafing during heavy lifts.",
    priceHistory: [599, 499, 429, 349, 349, 349],
    folder: "sportswear",
    photoId: "1583743814966-8936f5b7be1a"
  }
];
